// Code generated by ent, DO NOT EDIT.

package projectconversationstepevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the projectconversationstepevent type in the database.
	Label = "project_conversation_step_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrincipalID holds the string denoting the principal_id field in the database.
	FieldPrincipalID = "principal_id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldConversationID holds the string denoting the conversation_id field in the database.
	FieldConversationID = "conversation_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldStepStatus holds the string denoting the step_status field in the database.
	FieldStepStatus = "step_status"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldSourceTraceEventID holds the string denoting the source_trace_event_id field in the database.
	FieldSourceTraceEventID = "source_trace_event_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the projectconversationstepevent in the database.
	Table = "project_conversation_step_events"
)

// Columns holds all SQL columns for projectconversationstepevent fields.
var Columns = []string{
	FieldID,
	FieldPrincipalID,
	FieldRunID,
	FieldConversationID,
	FieldProjectID,
	FieldStepStatus,
	FieldSummary,
	FieldSourceTraceEventID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StepStatusValidator is a validator for the "step_status" field. It is called by the builders before save.
	StepStatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ProjectConversationStepEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrincipalID orders the results by the principal_id field.
func ByPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByConversationID orders the results by the conversation_id field.
func ByConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversationID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByStepStatus orders the results by the step_status field.
func ByStepStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepStatus, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// BySourceTraceEventID orders the results by the source_trace_event_id field.
func BySourceTraceEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceTraceEventID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
