// Code generated by ent, DO NOT EDIT.

package projectconversationrun

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the projectconversationrun type in the database.
	Label = "project_conversation_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrincipalID holds the string denoting the principal_id field in the database.
	FieldPrincipalID = "principal_id"
	// FieldConversationID holds the string denoting the conversation_id field in the database.
	FieldConversationID = "conversation_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldTurnID holds the string denoting the turn_id field in the database.
	FieldTurnID = "turn_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldWorkspacePath holds the string denoting the workspace_path field in the database.
	FieldWorkspacePath = "workspace_path"
	// FieldProviderThreadID holds the string denoting the provider_thread_id field in the database.
	FieldProviderThreadID = "provider_thread_id"
	// FieldProviderTurnID holds the string denoting the provider_turn_id field in the database.
	FieldProviderTurnID = "provider_turn_id"
	// FieldRuntimeStartedAt holds the string denoting the runtime_started_at field in the database.
	FieldRuntimeStartedAt = "runtime_started_at"
	// FieldTerminalAt holds the string denoting the terminal_at field in the database.
	FieldTerminalAt = "terminal_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldLastHeartbeatAt holds the string denoting the last_heartbeat_at field in the database.
	FieldLastHeartbeatAt = "last_heartbeat_at"
	// FieldCostAmount holds the string denoting the cost_amount field in the database.
	FieldCostAmount = "cost_amount"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldCachedInputTokens holds the string denoting the cached_input_tokens field in the database.
	FieldCachedInputTokens = "cached_input_tokens"
	// FieldCacheCreationTokens holds the string denoting the cache_creation_tokens field in the database.
	FieldCacheCreationTokens = "cache_creation_tokens"
	// FieldReasoningTokens holds the string denoting the reasoning_tokens field in the database.
	FieldReasoningTokens = "reasoning_tokens"
	// FieldPromptTokens holds the string denoting the prompt_tokens field in the database.
	FieldPromptTokens = "prompt_tokens"
	// FieldCandidateTokens holds the string denoting the candidate_tokens field in the database.
	FieldCandidateTokens = "candidate_tokens"
	// FieldToolTokens holds the string denoting the tool_tokens field in the database.
	FieldToolTokens = "tool_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldCurrentStepStatus holds the string denoting the current_step_status field in the database.
	FieldCurrentStepStatus = "current_step_status"
	// FieldCurrentStepSummary holds the string denoting the current_step_summary field in the database.
	FieldCurrentStepSummary = "current_step_summary"
	// FieldCurrentStepChangedAt holds the string denoting the current_step_changed_at field in the database.
	FieldCurrentStepChangedAt = "current_step_changed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the projectconversationrun in the database.
	Table = "project_conversation_runs"
)

// Columns holds all SQL columns for projectconversationrun fields.
var Columns = []string{
	FieldID,
	FieldPrincipalID,
	FieldConversationID,
	FieldProjectID,
	FieldProviderID,
	FieldTurnID,
	FieldStatus,
	FieldSessionID,
	FieldWorkspacePath,
	FieldProviderThreadID,
	FieldProviderTurnID,
	FieldRuntimeStartedAt,
	FieldTerminalAt,
	FieldLastError,
	FieldLastHeartbeatAt,
	FieldCostAmount,
	FieldInputTokens,
	FieldOutputTokens,
	FieldCachedInputTokens,
	FieldCacheCreationTokens,
	FieldReasoningTokens,
	FieldPromptTokens,
	FieldCandidateTokens,
	FieldToolTokens,
	FieldTotalTokens,
	FieldCurrentStepStatus,
	FieldCurrentStepSummary,
	FieldCurrentStepChangedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCostAmount holds the default value on creation for the "cost_amount" field.
	DefaultCostAmount float64
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int64
	// DefaultCachedInputTokens holds the default value on creation for the "cached_input_tokens" field.
	DefaultCachedInputTokens int64
	// DefaultCacheCreationTokens holds the default value on creation for the "cache_creation_tokens" field.
	DefaultCacheCreationTokens int64
	// DefaultReasoningTokens holds the default value on creation for the "reasoning_tokens" field.
	DefaultReasoningTokens int64
	// DefaultPromptTokens holds the default value on creation for the "prompt_tokens" field.
	DefaultPromptTokens int64
	// DefaultCandidateTokens holds the default value on creation for the "candidate_tokens" field.
	DefaultCandidateTokens int64
	// DefaultToolTokens holds the default value on creation for the "tool_tokens" field.
	DefaultToolTokens int64
	// DefaultTotalTokens holds the default value on creation for the "total_tokens" field.
	DefaultTotalTokens int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusLaunching   Status = "launching"
	StatusExecuting   Status = "executing"
	StatusInterrupted Status = "interrupted"
	StatusCompleted   Status = "completed"
	StatusFailed      Status = "failed"
	StatusTerminated  Status = "terminated"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusLaunching, StatusExecuting, StatusInterrupted, StatusCompleted, StatusFailed, StatusTerminated:
		return nil
	default:
		return fmt.Errorf("projectconversationrun: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ProjectConversationRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrincipalID orders the results by the principal_id field.
func ByPrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalID, opts...).ToFunc()
}

// ByConversationID orders the results by the conversation_id field.
func ByConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversationID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByTurnID orders the results by the turn_id field.
func ByTurnID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTurnID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByWorkspacePath orders the results by the workspace_path field.
func ByWorkspacePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspacePath, opts...).ToFunc()
}

// ByProviderThreadID orders the results by the provider_thread_id field.
func ByProviderThreadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderThreadID, opts...).ToFunc()
}

// ByProviderTurnID orders the results by the provider_turn_id field.
func ByProviderTurnID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderTurnID, opts...).ToFunc()
}

// ByRuntimeStartedAt orders the results by the runtime_started_at field.
func ByRuntimeStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntimeStartedAt, opts...).ToFunc()
}

// ByTerminalAt orders the results by the terminal_at field.
func ByTerminalAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTerminalAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByLastHeartbeatAt orders the results by the last_heartbeat_at field.
func ByLastHeartbeatAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastHeartbeatAt, opts...).ToFunc()
}

// ByCostAmount orders the results by the cost_amount field.
func ByCostAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostAmount, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByCachedInputTokens orders the results by the cached_input_tokens field.
func ByCachedInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedInputTokens, opts...).ToFunc()
}

// ByCacheCreationTokens orders the results by the cache_creation_tokens field.
func ByCacheCreationTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationTokens, opts...).ToFunc()
}

// ByReasoningTokens orders the results by the reasoning_tokens field.
func ByReasoningTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningTokens, opts...).ToFunc()
}

// ByPromptTokens orders the results by the prompt_tokens field.
func ByPromptTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptTokens, opts...).ToFunc()
}

// ByCandidateTokens orders the results by the candidate_tokens field.
func ByCandidateTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCandidateTokens, opts...).ToFunc()
}

// ByToolTokens orders the results by the tool_tokens field.
func ByToolTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByCurrentStepStatus orders the results by the current_step_status field.
func ByCurrentStepStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentStepStatus, opts...).ToFunc()
}

// ByCurrentStepSummary orders the results by the current_step_summary field.
func ByCurrentStepSummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentStepSummary, opts...).ToFunc()
}

// ByCurrentStepChangedAt orders the results by the current_step_changed_at field.
func ByCurrentStepChangedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentStepChangedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
