import type { StatusPayload } from '$lib/api/contracts'

export const stageOrderedStatusPayloadFixture: StatusPayload = {
  stages: [
    {
      id: 'stage-1',
      project_id: 'project-1',
      key: 'backlog',
      name: 'Backlog',
      position: 1,
      active_runs: 0,
      max_active_runs: null,
      description: '',
    },
    {
      id: 'stage-2',
      project_id: 'project-1',
      key: 'execution',
      name: 'Execution',
      position: 2,
      active_runs: 1,
      max_active_runs: 1,
      description: 'Agent work in flight.',
    },
  ],
  stage_groups: [
    {
      stage: {
        id: 'stage-1',
        project_id: 'project-1',
        key: 'backlog',
        name: 'Backlog',
        position: 1,
        active_runs: 0,
        max_active_runs: null,
        description: '',
      },
      statuses: [
        {
          id: 'status-1',
          project_id: 'project-1',
          stage_id: 'stage-1',
          stage: null,
          name: 'Todo',
          color: '#2563eb',
          icon: '',
          is_default: true,
          description: '',
          position: 2,
        },
      ],
    },
    {
      stage: {
        id: 'stage-2',
        project_id: 'project-1',
        key: 'execution',
        name: 'Execution',
        position: 2,
        active_runs: 1,
        max_active_runs: 1,
        description: 'Agent work in flight.',
      },
      statuses: [
        {
          id: 'status-2',
          project_id: 'project-1',
          stage_id: 'stage-2',
          stage: null,
          name: 'Doing',
          color: '#f59e0b',
          icon: '',
          is_default: false,
          description: '',
          position: 1,
        },
      ],
    },
    {
      stage: null,
      statuses: [
        {
          id: 'status-3',
          project_id: 'project-1',
          stage_id: null,
          stage: null,
          name: 'Inbox',
          color: '#64748b',
          icon: '',
          is_default: false,
          description: '',
          position: 1,
        },
      ],
    },
  ],
  statuses: [
    {
      id: 'status-3',
      project_id: 'project-1',
      stage_id: null,
      stage: null,
      name: 'Inbox',
      color: '#64748b',
      icon: '',
      is_default: false,
      description: '',
      position: 1,
    },
    {
      id: 'status-2',
      project_id: 'project-1',
      stage_id: 'stage-2',
      stage: null,
      name: 'Doing',
      color: '#f59e0b',
      icon: '',
      is_default: false,
      description: '',
      position: 1,
    },
    {
      id: 'status-1',
      project_id: 'project-1',
      stage_id: 'stage-1',
      stage: null,
      name: 'Todo',
      color: '#2563eb',
      icon: '',
      is_default: true,
      description: '',
      position: 2,
    },
  ],
}
