// Code generated by ent, DO NOT EDIT.

package skillversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the skillversion type in the database.
	Label = "skill_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSkillID holds the string denoting the skill_id field in the database.
	FieldSkillID = "skill_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldContentMarkdown holds the string denoting the content_markdown field in the database.
	FieldContentMarkdown = "content_markdown"
	// FieldContentHash holds the string denoting the content_hash field in the database.
	FieldContentHash = "content_hash"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSkill holds the string denoting the skill edge name in mutations.
	EdgeSkill = "skill"
	// EdgeRequiredByBindings holds the string denoting the required_by_bindings edge name in mutations.
	EdgeRequiredByBindings = "required_by_bindings"
	// Table holds the table name of the skillversion in the database.
	Table = "skill_versions"
	// SkillTable is the table that holds the skill relation/edge.
	SkillTable = "skill_versions"
	// SkillInverseTable is the table name for the Skill entity.
	// It exists in this package in order to avoid circular dependency with the "skill" package.
	SkillInverseTable = "skills"
	// SkillColumn is the table column denoting the skill relation/edge.
	SkillColumn = "skill_id"
	// RequiredByBindingsTable is the table that holds the required_by_bindings relation/edge.
	RequiredByBindingsTable = "workflow_skill_bindings"
	// RequiredByBindingsInverseTable is the table name for the WorkflowSkillBinding entity.
	// It exists in this package in order to avoid circular dependency with the "workflowskillbinding" package.
	RequiredByBindingsInverseTable = "workflow_skill_bindings"
	// RequiredByBindingsColumn is the table column denoting the required_by_bindings relation/edge.
	RequiredByBindingsColumn = "required_version_id"
)

// Columns holds all SQL columns for skillversion fields.
var Columns = []string{
	FieldID,
	FieldSkillID,
	FieldVersion,
	FieldContentMarkdown,
	FieldContentHash,
	FieldCreatedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ContentHashValidator is a validator for the "content_hash" field. It is called by the builders before save.
	ContentHashValidator func(string) error
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SkillVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySkillID orders the results by the skill_id field.
func BySkillID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByContentMarkdown orders the results by the content_markdown field.
func ByContentMarkdown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentMarkdown, opts...).ToFunc()
}

// ByContentHash orders the results by the content_hash field.
func ByContentHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentHash, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySkillField orders the results by skill field.
func BySkillField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSkillStep(), sql.OrderByField(field, opts...))
	}
}

// ByRequiredByBindingsCount orders the results by required_by_bindings count.
func ByRequiredByBindingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRequiredByBindingsStep(), opts...)
	}
}

// ByRequiredByBindings orders the results by required_by_bindings terms.
func ByRequiredByBindings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequiredByBindingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSkillStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SkillInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SkillTable, SkillColumn),
	)
}
func newRequiredByBindingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequiredByBindingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RequiredByBindingsTable, RequiredByBindingsColumn),
	)
}
