import type { Agent, AgentProvider, AgentRun, Ticket, Workflow } from '$lib/api/contracts'

export const providerFixture: AgentProvider = {
  id: 'provider-1',
  organization_id: 'org-1',
  machine_id: 'machine-1',
  machine_name: 'local',
  machine_host: '127.0.0.1',
  machine_status: 'online',
  machine_ssh_user: null,
  machine_workspace_root: '/workspace',
  name: 'Codex',
  adapter_type: 'codex-app-server',
  permission_profile: 'unrestricted',
  available: true,
  availability_checked_at: '2026-03-27T10:00:00Z',
  availability_reason: null,
  availability_state: 'available',
  capabilities: {
    ephemeral_chat: {
      state: 'available',
      reason: null,
    },
  },
  cli_command: 'codex',
  cli_args: ['app-server', '--listen', 'stdio://'],
  auth_config: {},
  cli_rate_limit: null,
  cli_rate_limit_updated_at: null,
  model_name: 'gpt-5.4',
  model_temperature: 0.1,
  model_max_tokens: 32000,
  max_parallel_runs: 2,
  cost_per_input_token: 0,
  cost_per_output_token: 0,
  pricing_config: {},
}

export const ticketsFixture: Ticket[] = [
  {
    id: 'ticket-1',
    project_id: 'project-1',
    identifier: 'ASE-101',
    title: 'Build runtime tab',
    description: '',
    status_id: 'status-1',
    status_name: 'In Progress',
    priority: 'high',
    type: 'feature',
    archived: false,
    workflow_id: 'workflow-1',
    current_run_id: 'run-1',
    target_machine_id: null,
    created_by: 'codex',
    parent: null,
    children: [],
    dependencies: [],
    external_links: [],
    external_ref: '',
    budget_usd: 0,
    cost_tokens_input: 0,
    cost_tokens_output: 0,
    cost_amount: 0,
    attempt_count: 0,
    consecutive_errors: 0,
    started_at: null,
    completed_at: null,
    next_retry_at: null,
    retry_paused: false,
    pause_reason: '',
    created_at: '2026-03-27T10:00:00Z',
  },
  {
    id: 'ticket-2',
    project_id: 'project-1',
    identifier: 'ASE-102',
    title: 'Show concurrent runs',
    description: '',
    status_id: 'status-1',
    status_name: 'In Progress',
    priority: 'medium',
    type: 'feature',
    archived: false,
    workflow_id: 'workflow-1',
    current_run_id: 'run-2',
    target_machine_id: null,
    created_by: 'codex',
    parent: null,
    children: [],
    dependencies: [],
    external_links: [],
    external_ref: '',
    budget_usd: 0,
    cost_tokens_input: 0,
    cost_tokens_output: 0,
    cost_amount: 0,
    attempt_count: 0,
    consecutive_errors: 0,
    started_at: null,
    completed_at: null,
    next_retry_at: null,
    retry_paused: false,
    pause_reason: '',
    created_at: '2026-03-27T10:01:00Z',
  },
]

export const workflowFixture: Workflow = {
  id: 'workflow-1',
  project_id: 'project-1',
  agent_id: 'agent-1',
  name: 'Coding',
  type: 'coding',
  workflow_family: 'coding',
  workflow_classification: {
    family: 'coding',
    confidence: 1,
    reasons: ['fixture'],
  },
  harness_path: '.openase/harnesses/coding.md',
  harness_content: null,
  hooks: {},
  max_concurrent: 2,
  max_retry_attempts: 0,
  timeout_minutes: 30,
  stall_timeout_minutes: 10,
  version: 1,
  is_active: true,
  pickup_status_ids: ['status-1'],
  finish_status_ids: ['status-2'],
}

export const agentFixture: Agent = {
  id: 'agent-1',
  provider_id: 'provider-1',
  project_id: 'project-1',
  name: 'Codex Worker',
  runtime_control_state: 'active',
  runtime: {
    active_run_count: 2,
    status: 'running',
    current_run_id: null,
    current_step_changed_at: null,
    current_step_status: null,
    current_step_summary: null,
    current_ticket_id: null,
    session_id: '',
    runtime_phase: 'executing',
    runtime_started_at: '2026-03-27T10:02:00Z',
    last_error: '',
    last_heartbeat_at: '2026-03-27T10:03:00Z',
  },
  total_tokens_used: 0,
  total_tickets_completed: 3,
}

export const agentRunsFixture: AgentRun[] = [
  {
    id: 'run-2',
    agent_id: 'agent-1',
    workflow_id: 'workflow-1',
    workflow_version_id: 'workflow-version-2',
    ticket_id: 'ticket-2',
    provider_id: 'provider-1',
    status: 'executing',
    session_id: 'session-2',
    skill_version_ids: ['skill-version-2'],
    runtime_started_at: '2026-03-27T10:02:00Z',
    last_error: '',
    last_heartbeat_at: '2026-03-27T10:03:00Z',
    terminal_at: null,
    created_at: '2026-03-27T10:02:00Z',
  },
  {
    id: 'run-1',
    agent_id: 'agent-1',
    workflow_id: 'workflow-1',
    workflow_version_id: 'workflow-version-1',
    ticket_id: 'ticket-1',
    provider_id: 'provider-1',
    status: 'ready',
    session_id: 'session-1',
    skill_version_ids: ['skill-version-1'],
    runtime_started_at: '2026-03-27T10:01:00Z',
    last_error: '',
    last_heartbeat_at: '2026-03-27T10:02:30Z',
    terminal_at: null,
    created_at: '2026-03-27T10:01:00Z',
  },
]
