// Code generated by ent, DO NOT EDIT.

package userapikey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/BetterAndBetterII/openase/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldUserID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldProjectID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldName, v))
}

// TokenPrefix applies equality check predicate on the "token_prefix" field. It's identical to TokenPrefixEQ.
func TokenPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldTokenPrefix, v))
}

// TokenHint applies equality check predicate on the "token_hint" field. It's identical to TokenHintEQ.
func TokenHint(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldTokenHint, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldTokenHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// DisabledAt applies equality check predicate on the "disabled_at" field. It's identical to DisabledAtEQ.
func DisabledAt(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldDisabledAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldRevokedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldUserID, vs...))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldProjectID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContainsFold(FieldName, v))
}

// TokenPrefixEQ applies the EQ predicate on the "token_prefix" field.
func TokenPrefixEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldTokenPrefix, v))
}

// TokenPrefixNEQ applies the NEQ predicate on the "token_prefix" field.
func TokenPrefixNEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldTokenPrefix, v))
}

// TokenPrefixIn applies the In predicate on the "token_prefix" field.
func TokenPrefixIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldTokenPrefix, vs...))
}

// TokenPrefixNotIn applies the NotIn predicate on the "token_prefix" field.
func TokenPrefixNotIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldTokenPrefix, vs...))
}

// TokenPrefixGT applies the GT predicate on the "token_prefix" field.
func TokenPrefixGT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldTokenPrefix, v))
}

// TokenPrefixGTE applies the GTE predicate on the "token_prefix" field.
func TokenPrefixGTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldTokenPrefix, v))
}

// TokenPrefixLT applies the LT predicate on the "token_prefix" field.
func TokenPrefixLT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldTokenPrefix, v))
}

// TokenPrefixLTE applies the LTE predicate on the "token_prefix" field.
func TokenPrefixLTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldTokenPrefix, v))
}

// TokenPrefixContains applies the Contains predicate on the "token_prefix" field.
func TokenPrefixContains(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContains(FieldTokenPrefix, v))
}

// TokenPrefixHasPrefix applies the HasPrefix predicate on the "token_prefix" field.
func TokenPrefixHasPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasPrefix(FieldTokenPrefix, v))
}

// TokenPrefixHasSuffix applies the HasSuffix predicate on the "token_prefix" field.
func TokenPrefixHasSuffix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasSuffix(FieldTokenPrefix, v))
}

// TokenPrefixEqualFold applies the EqualFold predicate on the "token_prefix" field.
func TokenPrefixEqualFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEqualFold(FieldTokenPrefix, v))
}

// TokenPrefixContainsFold applies the ContainsFold predicate on the "token_prefix" field.
func TokenPrefixContainsFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContainsFold(FieldTokenPrefix, v))
}

// TokenHintEQ applies the EQ predicate on the "token_hint" field.
func TokenHintEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldTokenHint, v))
}

// TokenHintNEQ applies the NEQ predicate on the "token_hint" field.
func TokenHintNEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldTokenHint, v))
}

// TokenHintIn applies the In predicate on the "token_hint" field.
func TokenHintIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldTokenHint, vs...))
}

// TokenHintNotIn applies the NotIn predicate on the "token_hint" field.
func TokenHintNotIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldTokenHint, vs...))
}

// TokenHintGT applies the GT predicate on the "token_hint" field.
func TokenHintGT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldTokenHint, v))
}

// TokenHintGTE applies the GTE predicate on the "token_hint" field.
func TokenHintGTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldTokenHint, v))
}

// TokenHintLT applies the LT predicate on the "token_hint" field.
func TokenHintLT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldTokenHint, v))
}

// TokenHintLTE applies the LTE predicate on the "token_hint" field.
func TokenHintLTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldTokenHint, v))
}

// TokenHintContains applies the Contains predicate on the "token_hint" field.
func TokenHintContains(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContains(FieldTokenHint, v))
}

// TokenHintHasPrefix applies the HasPrefix predicate on the "token_hint" field.
func TokenHintHasPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasPrefix(FieldTokenHint, v))
}

// TokenHintHasSuffix applies the HasSuffix predicate on the "token_hint" field.
func TokenHintHasSuffix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasSuffix(FieldTokenHint, v))
}

// TokenHintEqualFold applies the EqualFold predicate on the "token_hint" field.
func TokenHintEqualFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEqualFold(FieldTokenHint, v))
}

// TokenHintContainsFold applies the ContainsFold predicate on the "token_hint" field.
func TokenHintContainsFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContainsFold(FieldTokenHint, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldContainsFold(FieldTokenHash, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldStatus, vs...))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotNull(FieldExpiresAt))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotNull(FieldLastUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// DisabledAtEQ applies the EQ predicate on the "disabled_at" field.
func DisabledAtEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldDisabledAt, v))
}

// DisabledAtNEQ applies the NEQ predicate on the "disabled_at" field.
func DisabledAtNEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldDisabledAt, v))
}

// DisabledAtIn applies the In predicate on the "disabled_at" field.
func DisabledAtIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldDisabledAt, vs...))
}

// DisabledAtNotIn applies the NotIn predicate on the "disabled_at" field.
func DisabledAtNotIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldDisabledAt, vs...))
}

// DisabledAtGT applies the GT predicate on the "disabled_at" field.
func DisabledAtGT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldDisabledAt, v))
}

// DisabledAtGTE applies the GTE predicate on the "disabled_at" field.
func DisabledAtGTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldDisabledAt, v))
}

// DisabledAtLT applies the LT predicate on the "disabled_at" field.
func DisabledAtLT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldDisabledAt, v))
}

// DisabledAtLTE applies the LTE predicate on the "disabled_at" field.
func DisabledAtLTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldDisabledAt, v))
}

// DisabledAtIsNil applies the IsNil predicate on the "disabled_at" field.
func DisabledAtIsNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIsNull(FieldDisabledAt))
}

// DisabledAtNotNil applies the NotNil predicate on the "disabled_at" field.
func DisabledAtNotNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotNull(FieldDisabledAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.FieldNotNull(FieldRevokedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserAPIKey {
	return predicate.UserAPIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserAPIKey {
	return predicate.UserAPIKey(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.UserAPIKey {
	return predicate.UserAPIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.UserAPIKey {
	return predicate.UserAPIKey(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAPIKey) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAPIKey) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAPIKey) predicate.UserAPIKey {
	return predicate.UserAPIKey(sql.NotPredicates(p))
}
