// Code generated by ent, DO NOT EDIT.

package skillblob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/BetterAndBetterII/openase/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldLTE(FieldID, id))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldSha256, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldSizeBytes, v))
}

// ContentBytes applies equality check predicate on the "content_bytes" field. It's identical to ContentBytesEQ.
func ContentBytes(v []byte) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldContentBytes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldCreatedAt, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldContainsFold(FieldSha256, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldLTE(FieldSizeBytes, v))
}

// CompressionEQ applies the EQ predicate on the "compression" field.
func CompressionEQ(v Compression) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldCompression, v))
}

// CompressionNEQ applies the NEQ predicate on the "compression" field.
func CompressionNEQ(v Compression) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNEQ(FieldCompression, v))
}

// CompressionIn applies the In predicate on the "compression" field.
func CompressionIn(vs ...Compression) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldIn(FieldCompression, vs...))
}

// CompressionNotIn applies the NotIn predicate on the "compression" field.
func CompressionNotIn(vs ...Compression) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNotIn(FieldCompression, vs...))
}

// ContentBytesEQ applies the EQ predicate on the "content_bytes" field.
func ContentBytesEQ(v []byte) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldContentBytes, v))
}

// ContentBytesNEQ applies the NEQ predicate on the "content_bytes" field.
func ContentBytesNEQ(v []byte) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNEQ(FieldContentBytes, v))
}

// ContentBytesIn applies the In predicate on the "content_bytes" field.
func ContentBytesIn(vs ...[]byte) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldIn(FieldContentBytes, vs...))
}

// ContentBytesNotIn applies the NotIn predicate on the "content_bytes" field.
func ContentBytesNotIn(vs ...[]byte) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNotIn(FieldContentBytes, vs...))
}

// ContentBytesGT applies the GT predicate on the "content_bytes" field.
func ContentBytesGT(v []byte) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldGT(FieldContentBytes, v))
}

// ContentBytesGTE applies the GTE predicate on the "content_bytes" field.
func ContentBytesGTE(v []byte) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldGTE(FieldContentBytes, v))
}

// ContentBytesLT applies the LT predicate on the "content_bytes" field.
func ContentBytesLT(v []byte) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldLT(FieldContentBytes, v))
}

// ContentBytesLTE applies the LTE predicate on the "content_bytes" field.
func ContentBytesLTE(v []byte) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldLTE(FieldContentBytes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SkillBlob {
	return predicate.SkillBlob(sql.FieldLTE(FieldCreatedAt, v))
}

// HasFiles applies the HasEdge predicate on the "files" edge.
func HasFiles() predicate.SkillBlob {
	return predicate.SkillBlob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FilesTable, FilesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFilesWith applies the HasEdge predicate on the "files" edge with a given conditions (other predicates).
func HasFilesWith(preds ...predicate.SkillVersionFile) predicate.SkillBlob {
	return predicate.SkillBlob(func(s *sql.Selector) {
		step := newFilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SkillBlob) predicate.SkillBlob {
	return predicate.SkillBlob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SkillBlob) predicate.SkillBlob {
	return predicate.SkillBlob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SkillBlob) predicate.SkillBlob {
	return predicate.SkillBlob(sql.NotPredicates(p))
}
