// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/agenttranscriptentry"
	"github.com/BetterAndBetterII/openase/ent/predicate"
)

// AgentTranscriptEntryDelete is the builder for deleting a AgentTranscriptEntry entity.
type AgentTranscriptEntryDelete struct {
	config
	hooks    []Hook
	mutation *AgentTranscriptEntryMutation
}

// Where appends a list predicates to the AgentTranscriptEntryDelete builder.
func (_d *AgentTranscriptEntryDelete) Where(ps ...predicate.AgentTranscriptEntry) *AgentTranscriptEntryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgentTranscriptEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentTranscriptEntryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgentTranscriptEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agenttranscriptentry.Table, sqlgraph.NewFieldSpec(agenttranscriptentry.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgentTranscriptEntryDeleteOne is the builder for deleting a single AgentTranscriptEntry entity.
type AgentTranscriptEntryDeleteOne struct {
	_d *AgentTranscriptEntryDelete
}

// Where appends a list predicates to the AgentTranscriptEntryDelete builder.
func (_d *AgentTranscriptEntryDeleteOne) Where(ps ...predicate.AgentTranscriptEntry) *AgentTranscriptEntryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgentTranscriptEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agenttranscriptentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentTranscriptEntryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
