// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/agent"
	"github.com/BetterAndBetterII/openase/ent/agentactivityinstance"
	"github.com/BetterAndBetterII/openase/ent/agentrun"
	"github.com/BetterAndBetterII/openase/ent/predicate"
	"github.com/BetterAndBetterII/openase/ent/project"
	"github.com/BetterAndBetterII/openase/ent/ticket"
	"github.com/google/uuid"
)

// AgentActivityInstanceUpdate is the builder for updating AgentActivityInstance entities.
type AgentActivityInstanceUpdate struct {
	config
	hooks    []Hook
	mutation *AgentActivityInstanceMutation
}

// Where appends a list predicates to the AgentActivityInstanceUpdate builder.
func (_u *AgentActivityInstanceUpdate) Where(ps ...predicate.AgentActivityInstance) *AgentActivityInstanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *AgentActivityInstanceUpdate) SetProjectID(v uuid.UUID) *AgentActivityInstanceUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableProjectID(v *uuid.UUID) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *AgentActivityInstanceUpdate) SetTicketID(v uuid.UUID) *AgentActivityInstanceUpdate {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableTicketID(v *uuid.UUID) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// ClearTicketID clears the value of the "ticket_id" field.
func (_u *AgentActivityInstanceUpdate) ClearTicketID() *AgentActivityInstanceUpdate {
	_u.mutation.ClearTicketID()
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *AgentActivityInstanceUpdate) SetAgentID(v uuid.UUID) *AgentActivityInstanceUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableAgentID(v *uuid.UUID) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetAgentRunID sets the "agent_run_id" field.
func (_u *AgentActivityInstanceUpdate) SetAgentRunID(v uuid.UUID) *AgentActivityInstanceUpdate {
	_u.mutation.SetAgentRunID(v)
	return _u
}

// SetNillableAgentRunID sets the "agent_run_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableAgentRunID(v *uuid.UUID) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetAgentRunID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AgentActivityInstanceUpdate) SetProvider(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableProvider(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetActivityKind sets the "activity_kind" field.
func (_u *AgentActivityInstanceUpdate) SetActivityKind(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetActivityKind(v)
	return _u
}

// SetNillableActivityKind sets the "activity_kind" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableActivityKind(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetActivityKind(*v)
	}
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *AgentActivityInstanceUpdate) SetActivityID(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableActivityID(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetIDSource sets the "id_source" field.
func (_u *AgentActivityInstanceUpdate) SetIDSource(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetIDSource(v)
	return _u
}

// SetNillableIDSource sets the "id_source" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableIDSource(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetIDSource(*v)
	}
	return _u
}

// SetIdentityConfidence sets the "identity_confidence" field.
func (_u *AgentActivityInstanceUpdate) SetIdentityConfidence(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetIdentityConfidence(v)
	return _u
}

// SetNillableIdentityConfidence sets the "identity_confidence" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableIdentityConfidence(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetIdentityConfidence(*v)
	}
	return _u
}

// SetParentActivityID sets the "parent_activity_id" field.
func (_u *AgentActivityInstanceUpdate) SetParentActivityID(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetParentActivityID(v)
	return _u
}

// SetNillableParentActivityID sets the "parent_activity_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableParentActivityID(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetParentActivityID(*v)
	}
	return _u
}

// ClearParentActivityID clears the value of the "parent_activity_id" field.
func (_u *AgentActivityInstanceUpdate) ClearParentActivityID() *AgentActivityInstanceUpdate {
	_u.mutation.ClearParentActivityID()
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *AgentActivityInstanceUpdate) SetThreadID(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableThreadID(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// ClearThreadID clears the value of the "thread_id" field.
func (_u *AgentActivityInstanceUpdate) ClearThreadID() *AgentActivityInstanceUpdate {
	_u.mutation.ClearThreadID()
	return _u
}

// SetTurnID sets the "turn_id" field.
func (_u *AgentActivityInstanceUpdate) SetTurnID(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetTurnID(v)
	return _u
}

// SetNillableTurnID sets the "turn_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableTurnID(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetTurnID(*v)
	}
	return _u
}

// ClearTurnID clears the value of the "turn_id" field.
func (_u *AgentActivityInstanceUpdate) ClearTurnID() *AgentActivityInstanceUpdate {
	_u.mutation.ClearTurnID()
	return _u
}

// SetCommand sets the "command" field.
func (_u *AgentActivityInstanceUpdate) SetCommand(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableCommand(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *AgentActivityInstanceUpdate) ClearCommand() *AgentActivityInstanceUpdate {
	_u.mutation.ClearCommand()
	return _u
}

// SetToolName sets the "tool_name" field.
func (_u *AgentActivityInstanceUpdate) SetToolName(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetToolName(v)
	return _u
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableToolName(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetToolName(*v)
	}
	return _u
}

// ClearToolName clears the value of the "tool_name" field.
func (_u *AgentActivityInstanceUpdate) ClearToolName() *AgentActivityInstanceUpdate {
	_u.mutation.ClearToolName()
	return _u
}

// SetTitle sets the "title" field.
func (_u *AgentActivityInstanceUpdate) SetTitle(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableTitle(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *AgentActivityInstanceUpdate) ClearTitle() *AgentActivityInstanceUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentActivityInstanceUpdate) SetStatus(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableStatus(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLiveText sets the "live_text" field.
func (_u *AgentActivityInstanceUpdate) SetLiveText(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetLiveText(v)
	return _u
}

// SetNillableLiveText sets the "live_text" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableLiveText(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetLiveText(*v)
	}
	return _u
}

// ClearLiveText clears the value of the "live_text" field.
func (_u *AgentActivityInstanceUpdate) ClearLiveText() *AgentActivityInstanceUpdate {
	_u.mutation.ClearLiveText()
	return _u
}

// SetFinalText sets the "final_text" field.
func (_u *AgentActivityInstanceUpdate) SetFinalText(v string) *AgentActivityInstanceUpdate {
	_u.mutation.SetFinalText(v)
	return _u
}

// SetNillableFinalText sets the "final_text" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableFinalText(v *string) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetFinalText(*v)
	}
	return _u
}

// ClearFinalText clears the value of the "final_text" field.
func (_u *AgentActivityInstanceUpdate) ClearFinalText() *AgentActivityInstanceUpdate {
	_u.mutation.ClearFinalText()
	return _u
}

// SetLiveTextBytes sets the "live_text_bytes" field.
func (_u *AgentActivityInstanceUpdate) SetLiveTextBytes(v int) *AgentActivityInstanceUpdate {
	_u.mutation.ResetLiveTextBytes()
	_u.mutation.SetLiveTextBytes(v)
	return _u
}

// SetNillableLiveTextBytes sets the "live_text_bytes" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableLiveTextBytes(v *int) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetLiveTextBytes(*v)
	}
	return _u
}

// AddLiveTextBytes adds value to the "live_text_bytes" field.
func (_u *AgentActivityInstanceUpdate) AddLiveTextBytes(v int) *AgentActivityInstanceUpdate {
	_u.mutation.AddLiveTextBytes(v)
	return _u
}

// SetFinalTextBytes sets the "final_text_bytes" field.
func (_u *AgentActivityInstanceUpdate) SetFinalTextBytes(v int) *AgentActivityInstanceUpdate {
	_u.mutation.ResetFinalTextBytes()
	_u.mutation.SetFinalTextBytes(v)
	return _u
}

// SetNillableFinalTextBytes sets the "final_text_bytes" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableFinalTextBytes(v *int) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetFinalTextBytes(*v)
	}
	return _u
}

// AddFinalTextBytes adds value to the "final_text_bytes" field.
func (_u *AgentActivityInstanceUpdate) AddFinalTextBytes(v int) *AgentActivityInstanceUpdate {
	_u.mutation.AddFinalTextBytes(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AgentActivityInstanceUpdate) SetMetadata(v map[string]interface{}) *AgentActivityInstanceUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *AgentActivityInstanceUpdate) SetStartedAt(v time.Time) *AgentActivityInstanceUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableStartedAt(v *time.Time) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *AgentActivityInstanceUpdate) ClearStartedAt() *AgentActivityInstanceUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentActivityInstanceUpdate) SetUpdatedAt(v time.Time) *AgentActivityInstanceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableUpdatedAt(v *time.Time) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *AgentActivityInstanceUpdate) SetCompletedAt(v time.Time) *AgentActivityInstanceUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdate) SetNillableCompletedAt(v *time.Time) *AgentActivityInstanceUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *AgentActivityInstanceUpdate) ClearCompletedAt() *AgentActivityInstanceUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *AgentActivityInstanceUpdate) SetProject(v *Project) *AgentActivityInstanceUpdate {
	return _u.SetProjectID(v.ID)
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_u *AgentActivityInstanceUpdate) SetTicket(v *Ticket) *AgentActivityInstanceUpdate {
	return _u.SetTicketID(v.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_u *AgentActivityInstanceUpdate) SetAgent(v *Agent) *AgentActivityInstanceUpdate {
	return _u.SetAgentID(v.ID)
}

// SetAgentRun sets the "agent_run" edge to the AgentRun entity.
func (_u *AgentActivityInstanceUpdate) SetAgentRun(v *AgentRun) *AgentActivityInstanceUpdate {
	return _u.SetAgentRunID(v.ID)
}

// Mutation returns the AgentActivityInstanceMutation object of the builder.
func (_u *AgentActivityInstanceUpdate) Mutation() *AgentActivityInstanceMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *AgentActivityInstanceUpdate) ClearProject() *AgentActivityInstanceUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (_u *AgentActivityInstanceUpdate) ClearTicket() *AgentActivityInstanceUpdate {
	_u.mutation.ClearTicket()
	return _u
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (_u *AgentActivityInstanceUpdate) ClearAgent() *AgentActivityInstanceUpdate {
	_u.mutation.ClearAgent()
	return _u
}

// ClearAgentRun clears the "agent_run" edge to the AgentRun entity.
func (_u *AgentActivityInstanceUpdate) ClearAgentRun() *AgentActivityInstanceUpdate {
	_u.mutation.ClearAgentRun()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentActivityInstanceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentActivityInstanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentActivityInstanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentActivityInstanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentActivityInstanceUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := agentactivityinstance.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActivityKind(); ok {
		if err := agentactivityinstance.ActivityKindValidator(v); err != nil {
			return &ValidationError{Name: "activity_kind", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.activity_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActivityID(); ok {
		if err := agentactivityinstance.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.activity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IDSource(); ok {
		if err := agentactivityinstance.IDSourceValidator(v); err != nil {
			return &ValidationError{Name: "id_source", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.id_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdentityConfidence(); ok {
		if err := agentactivityinstance.IdentityConfidenceValidator(v); err != nil {
			return &ValidationError{Name: "identity_confidence", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.identity_confidence": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agentactivityinstance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.status": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentActivityInstance.project"`)
	}
	if _u.mutation.AgentCleared() && len(_u.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentActivityInstance.agent"`)
	}
	if _u.mutation.AgentRunCleared() && len(_u.mutation.AgentRunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentActivityInstance.agent_run"`)
	}
	return nil
}

func (_u *AgentActivityInstanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentactivityinstance.Table, agentactivityinstance.Columns, sqlgraph.NewFieldSpec(agentactivityinstance.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(agentactivityinstance.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActivityKind(); ok {
		_spec.SetField(agentactivityinstance.FieldActivityKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActivityID(); ok {
		_spec.SetField(agentactivityinstance.FieldActivityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IDSource(); ok {
		_spec.SetField(agentactivityinstance.FieldIDSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdentityConfidence(); ok {
		_spec.SetField(agentactivityinstance.FieldIdentityConfidence, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentActivityID(); ok {
		_spec.SetField(agentactivityinstance.FieldParentActivityID, field.TypeString, value)
	}
	if _u.mutation.ParentActivityIDCleared() {
		_spec.ClearField(agentactivityinstance.FieldParentActivityID, field.TypeString)
	}
	if value, ok := _u.mutation.ThreadID(); ok {
		_spec.SetField(agentactivityinstance.FieldThreadID, field.TypeString, value)
	}
	if _u.mutation.ThreadIDCleared() {
		_spec.ClearField(agentactivityinstance.FieldThreadID, field.TypeString)
	}
	if value, ok := _u.mutation.TurnID(); ok {
		_spec.SetField(agentactivityinstance.FieldTurnID, field.TypeString, value)
	}
	if _u.mutation.TurnIDCleared() {
		_spec.ClearField(agentactivityinstance.FieldTurnID, field.TypeString)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(agentactivityinstance.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(agentactivityinstance.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.ToolName(); ok {
		_spec.SetField(agentactivityinstance.FieldToolName, field.TypeString, value)
	}
	if _u.mutation.ToolNameCleared() {
		_spec.ClearField(agentactivityinstance.FieldToolName, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(agentactivityinstance.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(agentactivityinstance.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentactivityinstance.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LiveText(); ok {
		_spec.SetField(agentactivityinstance.FieldLiveText, field.TypeString, value)
	}
	if _u.mutation.LiveTextCleared() {
		_spec.ClearField(agentactivityinstance.FieldLiveText, field.TypeString)
	}
	if value, ok := _u.mutation.FinalText(); ok {
		_spec.SetField(agentactivityinstance.FieldFinalText, field.TypeString, value)
	}
	if _u.mutation.FinalTextCleared() {
		_spec.ClearField(agentactivityinstance.FieldFinalText, field.TypeString)
	}
	if value, ok := _u.mutation.LiveTextBytes(); ok {
		_spec.SetField(agentactivityinstance.FieldLiveTextBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLiveTextBytes(); ok {
		_spec.AddField(agentactivityinstance.FieldLiveTextBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FinalTextBytes(); ok {
		_spec.SetField(agentactivityinstance.FieldFinalTextBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFinalTextBytes(); ok {
		_spec.AddField(agentactivityinstance.FieldFinalTextBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(agentactivityinstance.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(agentactivityinstance.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(agentactivityinstance.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentactivityinstance.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(agentactivityinstance.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(agentactivityinstance.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.ProjectTable,
			Columns: []string{agentactivityinstance.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.ProjectTable,
			Columns: []string{agentactivityinstance.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.TicketTable,
			Columns: []string{agentactivityinstance.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.TicketTable,
			Columns: []string{agentactivityinstance.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.AgentTable,
			Columns: []string{agentactivityinstance.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.AgentTable,
			Columns: []string{agentactivityinstance.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentRunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.AgentRunTable,
			Columns: []string{agentactivityinstance.AgentRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentrun.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.AgentRunTable,
			Columns: []string{agentactivityinstance.AgentRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentactivityinstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentActivityInstanceUpdateOne is the builder for updating a single AgentActivityInstance entity.
type AgentActivityInstanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentActivityInstanceMutation
}

// SetProjectID sets the "project_id" field.
func (_u *AgentActivityInstanceUpdateOne) SetProjectID(v uuid.UUID) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableProjectID(v *uuid.UUID) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *AgentActivityInstanceUpdateOne) SetTicketID(v uuid.UUID) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableTicketID(v *uuid.UUID) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// ClearTicketID clears the value of the "ticket_id" field.
func (_u *AgentActivityInstanceUpdateOne) ClearTicketID() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearTicketID()
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *AgentActivityInstanceUpdateOne) SetAgentID(v uuid.UUID) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableAgentID(v *uuid.UUID) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetAgentRunID sets the "agent_run_id" field.
func (_u *AgentActivityInstanceUpdateOne) SetAgentRunID(v uuid.UUID) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetAgentRunID(v)
	return _u
}

// SetNillableAgentRunID sets the "agent_run_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableAgentRunID(v *uuid.UUID) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetAgentRunID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AgentActivityInstanceUpdateOne) SetProvider(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableProvider(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetActivityKind sets the "activity_kind" field.
func (_u *AgentActivityInstanceUpdateOne) SetActivityKind(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetActivityKind(v)
	return _u
}

// SetNillableActivityKind sets the "activity_kind" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableActivityKind(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetActivityKind(*v)
	}
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *AgentActivityInstanceUpdateOne) SetActivityID(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableActivityID(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetIDSource sets the "id_source" field.
func (_u *AgentActivityInstanceUpdateOne) SetIDSource(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetIDSource(v)
	return _u
}

// SetNillableIDSource sets the "id_source" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableIDSource(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetIDSource(*v)
	}
	return _u
}

// SetIdentityConfidence sets the "identity_confidence" field.
func (_u *AgentActivityInstanceUpdateOne) SetIdentityConfidence(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetIdentityConfidence(v)
	return _u
}

// SetNillableIdentityConfidence sets the "identity_confidence" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableIdentityConfidence(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetIdentityConfidence(*v)
	}
	return _u
}

// SetParentActivityID sets the "parent_activity_id" field.
func (_u *AgentActivityInstanceUpdateOne) SetParentActivityID(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetParentActivityID(v)
	return _u
}

// SetNillableParentActivityID sets the "parent_activity_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableParentActivityID(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetParentActivityID(*v)
	}
	return _u
}

// ClearParentActivityID clears the value of the "parent_activity_id" field.
func (_u *AgentActivityInstanceUpdateOne) ClearParentActivityID() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearParentActivityID()
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *AgentActivityInstanceUpdateOne) SetThreadID(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableThreadID(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// ClearThreadID clears the value of the "thread_id" field.
func (_u *AgentActivityInstanceUpdateOne) ClearThreadID() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearThreadID()
	return _u
}

// SetTurnID sets the "turn_id" field.
func (_u *AgentActivityInstanceUpdateOne) SetTurnID(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetTurnID(v)
	return _u
}

// SetNillableTurnID sets the "turn_id" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableTurnID(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetTurnID(*v)
	}
	return _u
}

// ClearTurnID clears the value of the "turn_id" field.
func (_u *AgentActivityInstanceUpdateOne) ClearTurnID() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearTurnID()
	return _u
}

// SetCommand sets the "command" field.
func (_u *AgentActivityInstanceUpdateOne) SetCommand(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableCommand(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *AgentActivityInstanceUpdateOne) ClearCommand() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearCommand()
	return _u
}

// SetToolName sets the "tool_name" field.
func (_u *AgentActivityInstanceUpdateOne) SetToolName(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetToolName(v)
	return _u
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableToolName(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetToolName(*v)
	}
	return _u
}

// ClearToolName clears the value of the "tool_name" field.
func (_u *AgentActivityInstanceUpdateOne) ClearToolName() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearToolName()
	return _u
}

// SetTitle sets the "title" field.
func (_u *AgentActivityInstanceUpdateOne) SetTitle(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableTitle(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *AgentActivityInstanceUpdateOne) ClearTitle() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentActivityInstanceUpdateOne) SetStatus(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableStatus(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLiveText sets the "live_text" field.
func (_u *AgentActivityInstanceUpdateOne) SetLiveText(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetLiveText(v)
	return _u
}

// SetNillableLiveText sets the "live_text" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableLiveText(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetLiveText(*v)
	}
	return _u
}

// ClearLiveText clears the value of the "live_text" field.
func (_u *AgentActivityInstanceUpdateOne) ClearLiveText() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearLiveText()
	return _u
}

// SetFinalText sets the "final_text" field.
func (_u *AgentActivityInstanceUpdateOne) SetFinalText(v string) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetFinalText(v)
	return _u
}

// SetNillableFinalText sets the "final_text" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableFinalText(v *string) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetFinalText(*v)
	}
	return _u
}

// ClearFinalText clears the value of the "final_text" field.
func (_u *AgentActivityInstanceUpdateOne) ClearFinalText() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearFinalText()
	return _u
}

// SetLiveTextBytes sets the "live_text_bytes" field.
func (_u *AgentActivityInstanceUpdateOne) SetLiveTextBytes(v int) *AgentActivityInstanceUpdateOne {
	_u.mutation.ResetLiveTextBytes()
	_u.mutation.SetLiveTextBytes(v)
	return _u
}

// SetNillableLiveTextBytes sets the "live_text_bytes" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableLiveTextBytes(v *int) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetLiveTextBytes(*v)
	}
	return _u
}

// AddLiveTextBytes adds value to the "live_text_bytes" field.
func (_u *AgentActivityInstanceUpdateOne) AddLiveTextBytes(v int) *AgentActivityInstanceUpdateOne {
	_u.mutation.AddLiveTextBytes(v)
	return _u
}

// SetFinalTextBytes sets the "final_text_bytes" field.
func (_u *AgentActivityInstanceUpdateOne) SetFinalTextBytes(v int) *AgentActivityInstanceUpdateOne {
	_u.mutation.ResetFinalTextBytes()
	_u.mutation.SetFinalTextBytes(v)
	return _u
}

// SetNillableFinalTextBytes sets the "final_text_bytes" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableFinalTextBytes(v *int) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetFinalTextBytes(*v)
	}
	return _u
}

// AddFinalTextBytes adds value to the "final_text_bytes" field.
func (_u *AgentActivityInstanceUpdateOne) AddFinalTextBytes(v int) *AgentActivityInstanceUpdateOne {
	_u.mutation.AddFinalTextBytes(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AgentActivityInstanceUpdateOne) SetMetadata(v map[string]interface{}) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *AgentActivityInstanceUpdateOne) SetStartedAt(v time.Time) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableStartedAt(v *time.Time) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *AgentActivityInstanceUpdateOne) ClearStartedAt() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentActivityInstanceUpdateOne) SetUpdatedAt(v time.Time) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableUpdatedAt(v *time.Time) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *AgentActivityInstanceUpdateOne) SetCompletedAt(v time.Time) *AgentActivityInstanceUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *AgentActivityInstanceUpdateOne) SetNillableCompletedAt(v *time.Time) *AgentActivityInstanceUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *AgentActivityInstanceUpdateOne) ClearCompletedAt() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *AgentActivityInstanceUpdateOne) SetProject(v *Project) *AgentActivityInstanceUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_u *AgentActivityInstanceUpdateOne) SetTicket(v *Ticket) *AgentActivityInstanceUpdateOne {
	return _u.SetTicketID(v.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_u *AgentActivityInstanceUpdateOne) SetAgent(v *Agent) *AgentActivityInstanceUpdateOne {
	return _u.SetAgentID(v.ID)
}

// SetAgentRun sets the "agent_run" edge to the AgentRun entity.
func (_u *AgentActivityInstanceUpdateOne) SetAgentRun(v *AgentRun) *AgentActivityInstanceUpdateOne {
	return _u.SetAgentRunID(v.ID)
}

// Mutation returns the AgentActivityInstanceMutation object of the builder.
func (_u *AgentActivityInstanceUpdateOne) Mutation() *AgentActivityInstanceMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *AgentActivityInstanceUpdateOne) ClearProject() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (_u *AgentActivityInstanceUpdateOne) ClearTicket() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearTicket()
	return _u
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (_u *AgentActivityInstanceUpdateOne) ClearAgent() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearAgent()
	return _u
}

// ClearAgentRun clears the "agent_run" edge to the AgentRun entity.
func (_u *AgentActivityInstanceUpdateOne) ClearAgentRun() *AgentActivityInstanceUpdateOne {
	_u.mutation.ClearAgentRun()
	return _u
}

// Where appends a list predicates to the AgentActivityInstanceUpdate builder.
func (_u *AgentActivityInstanceUpdateOne) Where(ps ...predicate.AgentActivityInstance) *AgentActivityInstanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentActivityInstanceUpdateOne) Select(field string, fields ...string) *AgentActivityInstanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentActivityInstance entity.
func (_u *AgentActivityInstanceUpdateOne) Save(ctx context.Context) (*AgentActivityInstance, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentActivityInstanceUpdateOne) SaveX(ctx context.Context) *AgentActivityInstance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentActivityInstanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentActivityInstanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentActivityInstanceUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := agentactivityinstance.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActivityKind(); ok {
		if err := agentactivityinstance.ActivityKindValidator(v); err != nil {
			return &ValidationError{Name: "activity_kind", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.activity_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActivityID(); ok {
		if err := agentactivityinstance.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.activity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IDSource(); ok {
		if err := agentactivityinstance.IDSourceValidator(v); err != nil {
			return &ValidationError{Name: "id_source", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.id_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdentityConfidence(); ok {
		if err := agentactivityinstance.IdentityConfidenceValidator(v); err != nil {
			return &ValidationError{Name: "identity_confidence", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.identity_confidence": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agentactivityinstance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentActivityInstance.status": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentActivityInstance.project"`)
	}
	if _u.mutation.AgentCleared() && len(_u.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentActivityInstance.agent"`)
	}
	if _u.mutation.AgentRunCleared() && len(_u.mutation.AgentRunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentActivityInstance.agent_run"`)
	}
	return nil
}

func (_u *AgentActivityInstanceUpdateOne) sqlSave(ctx context.Context) (_node *AgentActivityInstance, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentactivityinstance.Table, agentactivityinstance.Columns, sqlgraph.NewFieldSpec(agentactivityinstance.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentActivityInstance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentactivityinstance.FieldID)
		for _, f := range fields {
			if !agentactivityinstance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentactivityinstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(agentactivityinstance.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActivityKind(); ok {
		_spec.SetField(agentactivityinstance.FieldActivityKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActivityID(); ok {
		_spec.SetField(agentactivityinstance.FieldActivityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IDSource(); ok {
		_spec.SetField(agentactivityinstance.FieldIDSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdentityConfidence(); ok {
		_spec.SetField(agentactivityinstance.FieldIdentityConfidence, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentActivityID(); ok {
		_spec.SetField(agentactivityinstance.FieldParentActivityID, field.TypeString, value)
	}
	if _u.mutation.ParentActivityIDCleared() {
		_spec.ClearField(agentactivityinstance.FieldParentActivityID, field.TypeString)
	}
	if value, ok := _u.mutation.ThreadID(); ok {
		_spec.SetField(agentactivityinstance.FieldThreadID, field.TypeString, value)
	}
	if _u.mutation.ThreadIDCleared() {
		_spec.ClearField(agentactivityinstance.FieldThreadID, field.TypeString)
	}
	if value, ok := _u.mutation.TurnID(); ok {
		_spec.SetField(agentactivityinstance.FieldTurnID, field.TypeString, value)
	}
	if _u.mutation.TurnIDCleared() {
		_spec.ClearField(agentactivityinstance.FieldTurnID, field.TypeString)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(agentactivityinstance.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(agentactivityinstance.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.ToolName(); ok {
		_spec.SetField(agentactivityinstance.FieldToolName, field.TypeString, value)
	}
	if _u.mutation.ToolNameCleared() {
		_spec.ClearField(agentactivityinstance.FieldToolName, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(agentactivityinstance.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(agentactivityinstance.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentactivityinstance.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LiveText(); ok {
		_spec.SetField(agentactivityinstance.FieldLiveText, field.TypeString, value)
	}
	if _u.mutation.LiveTextCleared() {
		_spec.ClearField(agentactivityinstance.FieldLiveText, field.TypeString)
	}
	if value, ok := _u.mutation.FinalText(); ok {
		_spec.SetField(agentactivityinstance.FieldFinalText, field.TypeString, value)
	}
	if _u.mutation.FinalTextCleared() {
		_spec.ClearField(agentactivityinstance.FieldFinalText, field.TypeString)
	}
	if value, ok := _u.mutation.LiveTextBytes(); ok {
		_spec.SetField(agentactivityinstance.FieldLiveTextBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLiveTextBytes(); ok {
		_spec.AddField(agentactivityinstance.FieldLiveTextBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FinalTextBytes(); ok {
		_spec.SetField(agentactivityinstance.FieldFinalTextBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFinalTextBytes(); ok {
		_spec.AddField(agentactivityinstance.FieldFinalTextBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(agentactivityinstance.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(agentactivityinstance.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(agentactivityinstance.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentactivityinstance.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(agentactivityinstance.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(agentactivityinstance.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.ProjectTable,
			Columns: []string{agentactivityinstance.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.ProjectTable,
			Columns: []string{agentactivityinstance.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.TicketTable,
			Columns: []string{agentactivityinstance.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.TicketTable,
			Columns: []string{agentactivityinstance.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.AgentTable,
			Columns: []string{agentactivityinstance.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.AgentTable,
			Columns: []string{agentactivityinstance.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentRunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.AgentRunTable,
			Columns: []string{agentactivityinstance.AgentRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentrun.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentRunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentactivityinstance.AgentRunTable,
			Columns: []string{agentactivityinstance.AgentRunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentActivityInstance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentactivityinstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
