// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/agent"
	"github.com/BetterAndBetterII/openase/ent/agentprovider"
	"github.com/BetterAndBetterII/openase/ent/agentrun"
	"github.com/BetterAndBetterII/openase/ent/machine"
	"github.com/BetterAndBetterII/openase/ent/organization"
	"github.com/BetterAndBetterII/openase/internal/types/pgarray"
	"github.com/google/uuid"
)

// AgentProviderCreate is the builder for creating a AgentProvider entity.
type AgentProviderCreate struct {
	config
	mutation *AgentProviderMutation
	hooks    []Hook
}

// SetOrganizationID sets the "organization_id" field.
func (_c *AgentProviderCreate) SetOrganizationID(v uuid.UUID) *AgentProviderCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetMachineID sets the "machine_id" field.
func (_c *AgentProviderCreate) SetMachineID(v uuid.UUID) *AgentProviderCreate {
	_c.mutation.SetMachineID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AgentProviderCreate) SetName(v string) *AgentProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAdapterType sets the "adapter_type" field.
func (_c *AgentProviderCreate) SetAdapterType(v agentprovider.AdapterType) *AgentProviderCreate {
	_c.mutation.SetAdapterType(v)
	return _c
}

// SetPermissionProfile sets the "permission_profile" field.
func (_c *AgentProviderCreate) SetPermissionProfile(v agentprovider.PermissionProfile) *AgentProviderCreate {
	_c.mutation.SetPermissionProfile(v)
	return _c
}

// SetNillablePermissionProfile sets the "permission_profile" field if the given value is not nil.
func (_c *AgentProviderCreate) SetNillablePermissionProfile(v *agentprovider.PermissionProfile) *AgentProviderCreate {
	if v != nil {
		_c.SetPermissionProfile(*v)
	}
	return _c
}

// SetCliCommand sets the "cli_command" field.
func (_c *AgentProviderCreate) SetCliCommand(v string) *AgentProviderCreate {
	_c.mutation.SetCliCommand(v)
	return _c
}

// SetCliArgs sets the "cli_args" field.
func (_c *AgentProviderCreate) SetCliArgs(v pgarray.StringArray) *AgentProviderCreate {
	_c.mutation.SetCliArgs(v)
	return _c
}

// SetAuthConfig sets the "auth_config" field.
func (_c *AgentProviderCreate) SetAuthConfig(v map[string]interface{}) *AgentProviderCreate {
	_c.mutation.SetAuthConfig(v)
	return _c
}

// SetCliRateLimit sets the "cli_rate_limit" field.
func (_c *AgentProviderCreate) SetCliRateLimit(v map[string]interface{}) *AgentProviderCreate {
	_c.mutation.SetCliRateLimit(v)
	return _c
}

// SetCliRateLimitUpdatedAt sets the "cli_rate_limit_updated_at" field.
func (_c *AgentProviderCreate) SetCliRateLimitUpdatedAt(v time.Time) *AgentProviderCreate {
	_c.mutation.SetCliRateLimitUpdatedAt(v)
	return _c
}

// SetNillableCliRateLimitUpdatedAt sets the "cli_rate_limit_updated_at" field if the given value is not nil.
func (_c *AgentProviderCreate) SetNillableCliRateLimitUpdatedAt(v *time.Time) *AgentProviderCreate {
	if v != nil {
		_c.SetCliRateLimitUpdatedAt(*v)
	}
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *AgentProviderCreate) SetModelName(v string) *AgentProviderCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetModelTemperature sets the "model_temperature" field.
func (_c *AgentProviderCreate) SetModelTemperature(v float64) *AgentProviderCreate {
	_c.mutation.SetModelTemperature(v)
	return _c
}

// SetNillableModelTemperature sets the "model_temperature" field if the given value is not nil.
func (_c *AgentProviderCreate) SetNillableModelTemperature(v *float64) *AgentProviderCreate {
	if v != nil {
		_c.SetModelTemperature(*v)
	}
	return _c
}

// SetModelMaxTokens sets the "model_max_tokens" field.
func (_c *AgentProviderCreate) SetModelMaxTokens(v int) *AgentProviderCreate {
	_c.mutation.SetModelMaxTokens(v)
	return _c
}

// SetNillableModelMaxTokens sets the "model_max_tokens" field if the given value is not nil.
func (_c *AgentProviderCreate) SetNillableModelMaxTokens(v *int) *AgentProviderCreate {
	if v != nil {
		_c.SetModelMaxTokens(*v)
	}
	return _c
}

// SetMaxParallelRuns sets the "max_parallel_runs" field.
func (_c *AgentProviderCreate) SetMaxParallelRuns(v int) *AgentProviderCreate {
	_c.mutation.SetMaxParallelRuns(v)
	return _c
}

// SetNillableMaxParallelRuns sets the "max_parallel_runs" field if the given value is not nil.
func (_c *AgentProviderCreate) SetNillableMaxParallelRuns(v *int) *AgentProviderCreate {
	if v != nil {
		_c.SetMaxParallelRuns(*v)
	}
	return _c
}

// SetCostPerInputToken sets the "cost_per_input_token" field.
func (_c *AgentProviderCreate) SetCostPerInputToken(v float64) *AgentProviderCreate {
	_c.mutation.SetCostPerInputToken(v)
	return _c
}

// SetNillableCostPerInputToken sets the "cost_per_input_token" field if the given value is not nil.
func (_c *AgentProviderCreate) SetNillableCostPerInputToken(v *float64) *AgentProviderCreate {
	if v != nil {
		_c.SetCostPerInputToken(*v)
	}
	return _c
}

// SetCostPerOutputToken sets the "cost_per_output_token" field.
func (_c *AgentProviderCreate) SetCostPerOutputToken(v float64) *AgentProviderCreate {
	_c.mutation.SetCostPerOutputToken(v)
	return _c
}

// SetNillableCostPerOutputToken sets the "cost_per_output_token" field if the given value is not nil.
func (_c *AgentProviderCreate) SetNillableCostPerOutputToken(v *float64) *AgentProviderCreate {
	if v != nil {
		_c.SetCostPerOutputToken(*v)
	}
	return _c
}

// SetPricingConfig sets the "pricing_config" field.
func (_c *AgentProviderCreate) SetPricingConfig(v map[string]interface{}) *AgentProviderCreate {
	_c.mutation.SetPricingConfig(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AgentProviderCreate) SetID(v uuid.UUID) *AgentProviderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentProviderCreate) SetNillableID(v *uuid.UUID) *AgentProviderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *AgentProviderCreate) SetOrganization(v *Organization) *AgentProviderCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetMachine sets the "machine" edge to the Machine entity.
func (_c *AgentProviderCreate) SetMachine(v *Machine) *AgentProviderCreate {
	return _c.SetMachineID(v.ID)
}

// AddAgentIDs adds the "agents" edge to the Agent entity by IDs.
func (_c *AgentProviderCreate) AddAgentIDs(ids ...uuid.UUID) *AgentProviderCreate {
	_c.mutation.AddAgentIDs(ids...)
	return _c
}

// AddAgents adds the "agents" edges to the Agent entity.
func (_c *AgentProviderCreate) AddAgents(v ...*Agent) *AgentProviderCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgentIDs(ids...)
}

// AddAgentRunIDs adds the "agent_runs" edge to the AgentRun entity by IDs.
func (_c *AgentProviderCreate) AddAgentRunIDs(ids ...uuid.UUID) *AgentProviderCreate {
	_c.mutation.AddAgentRunIDs(ids...)
	return _c
}

// AddAgentRuns adds the "agent_runs" edges to the AgentRun entity.
func (_c *AgentProviderCreate) AddAgentRuns(v ...*AgentRun) *AgentProviderCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgentRunIDs(ids...)
}

// Mutation returns the AgentProviderMutation object of the builder.
func (_c *AgentProviderCreate) Mutation() *AgentProviderMutation {
	return _c.mutation
}

// Save creates the AgentProvider in the database.
func (_c *AgentProviderCreate) Save(ctx context.Context) (*AgentProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentProviderCreate) SaveX(ctx context.Context) *AgentProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentProviderCreate) defaults() {
	if _, ok := _c.mutation.PermissionProfile(); !ok {
		v := agentprovider.DefaultPermissionProfile
		_c.mutation.SetPermissionProfile(v)
	}
	if _, ok := _c.mutation.AuthConfig(); !ok {
		v := agentprovider.DefaultAuthConfig()
		_c.mutation.SetAuthConfig(v)
	}
	if _, ok := _c.mutation.CliRateLimit(); !ok {
		v := agentprovider.DefaultCliRateLimit()
		_c.mutation.SetCliRateLimit(v)
	}
	if _, ok := _c.mutation.ModelTemperature(); !ok {
		v := agentprovider.DefaultModelTemperature
		_c.mutation.SetModelTemperature(v)
	}
	if _, ok := _c.mutation.ModelMaxTokens(); !ok {
		v := agentprovider.DefaultModelMaxTokens
		_c.mutation.SetModelMaxTokens(v)
	}
	if _, ok := _c.mutation.MaxParallelRuns(); !ok {
		v := agentprovider.DefaultMaxParallelRuns
		_c.mutation.SetMaxParallelRuns(v)
	}
	if _, ok := _c.mutation.CostPerInputToken(); !ok {
		v := agentprovider.DefaultCostPerInputToken
		_c.mutation.SetCostPerInputToken(v)
	}
	if _, ok := _c.mutation.CostPerOutputToken(); !ok {
		v := agentprovider.DefaultCostPerOutputToken
		_c.mutation.SetCostPerOutputToken(v)
	}
	if _, ok := _c.mutation.PricingConfig(); !ok {
		v := agentprovider.DefaultPricingConfig()
		_c.mutation.SetPricingConfig(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := agentprovider.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentProviderCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "AgentProvider.organization_id"`)}
	}
	if _, ok := _c.mutation.MachineID(); !ok {
		return &ValidationError{Name: "machine_id", err: errors.New(`ent: missing required field "AgentProvider.machine_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AgentProvider.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := agentprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentProvider.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AdapterType(); !ok {
		return &ValidationError{Name: "adapter_type", err: errors.New(`ent: missing required field "AgentProvider.adapter_type"`)}
	}
	if v, ok := _c.mutation.AdapterType(); ok {
		if err := agentprovider.AdapterTypeValidator(v); err != nil {
			return &ValidationError{Name: "adapter_type", err: fmt.Errorf(`ent: validator failed for field "AgentProvider.adapter_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PermissionProfile(); !ok {
		return &ValidationError{Name: "permission_profile", err: errors.New(`ent: missing required field "AgentProvider.permission_profile"`)}
	}
	if v, ok := _c.mutation.PermissionProfile(); ok {
		if err := agentprovider.PermissionProfileValidator(v); err != nil {
			return &ValidationError{Name: "permission_profile", err: fmt.Errorf(`ent: validator failed for field "AgentProvider.permission_profile": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CliCommand(); !ok {
		return &ValidationError{Name: "cli_command", err: errors.New(`ent: missing required field "AgentProvider.cli_command"`)}
	}
	if v, ok := _c.mutation.CliCommand(); ok {
		if err := agentprovider.CliCommandValidator(v); err != nil {
			return &ValidationError{Name: "cli_command", err: fmt.Errorf(`ent: validator failed for field "AgentProvider.cli_command": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthConfig(); !ok {
		return &ValidationError{Name: "auth_config", err: errors.New(`ent: missing required field "AgentProvider.auth_config"`)}
	}
	if _, ok := _c.mutation.CliRateLimit(); !ok {
		return &ValidationError{Name: "cli_rate_limit", err: errors.New(`ent: missing required field "AgentProvider.cli_rate_limit"`)}
	}
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "AgentProvider.model_name"`)}
	}
	if v, ok := _c.mutation.ModelName(); ok {
		if err := agentprovider.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "AgentProvider.model_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelTemperature(); !ok {
		return &ValidationError{Name: "model_temperature", err: errors.New(`ent: missing required field "AgentProvider.model_temperature"`)}
	}
	if _, ok := _c.mutation.ModelMaxTokens(); !ok {
		return &ValidationError{Name: "model_max_tokens", err: errors.New(`ent: missing required field "AgentProvider.model_max_tokens"`)}
	}
	if _, ok := _c.mutation.MaxParallelRuns(); !ok {
		return &ValidationError{Name: "max_parallel_runs", err: errors.New(`ent: missing required field "AgentProvider.max_parallel_runs"`)}
	}
	if _, ok := _c.mutation.CostPerInputToken(); !ok {
		return &ValidationError{Name: "cost_per_input_token", err: errors.New(`ent: missing required field "AgentProvider.cost_per_input_token"`)}
	}
	if _, ok := _c.mutation.CostPerOutputToken(); !ok {
		return &ValidationError{Name: "cost_per_output_token", err: errors.New(`ent: missing required field "AgentProvider.cost_per_output_token"`)}
	}
	if _, ok := _c.mutation.PricingConfig(); !ok {
		return &ValidationError{Name: "pricing_config", err: errors.New(`ent: missing required field "AgentProvider.pricing_config"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "AgentProvider.organization"`)}
	}
	if len(_c.mutation.MachineIDs()) == 0 {
		return &ValidationError{Name: "machine", err: errors.New(`ent: missing required edge "AgentProvider.machine"`)}
	}
	return nil
}

func (_c *AgentProviderCreate) sqlSave(ctx context.Context) (*AgentProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentProviderCreate) createSpec() (*AgentProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentprovider.Table, sqlgraph.NewFieldSpec(agentprovider.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agentprovider.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AdapterType(); ok {
		_spec.SetField(agentprovider.FieldAdapterType, field.TypeEnum, value)
		_node.AdapterType = value
	}
	if value, ok := _c.mutation.PermissionProfile(); ok {
		_spec.SetField(agentprovider.FieldPermissionProfile, field.TypeEnum, value)
		_node.PermissionProfile = value
	}
	if value, ok := _c.mutation.CliCommand(); ok {
		_spec.SetField(agentprovider.FieldCliCommand, field.TypeString, value)
		_node.CliCommand = value
	}
	if value, ok := _c.mutation.CliArgs(); ok {
		_spec.SetField(agentprovider.FieldCliArgs, field.TypeOther, value)
		_node.CliArgs = value
	}
	if value, ok := _c.mutation.AuthConfig(); ok {
		_spec.SetField(agentprovider.FieldAuthConfig, field.TypeJSON, value)
		_node.AuthConfig = value
	}
	if value, ok := _c.mutation.CliRateLimit(); ok {
		_spec.SetField(agentprovider.FieldCliRateLimit, field.TypeJSON, value)
		_node.CliRateLimit = value
	}
	if value, ok := _c.mutation.CliRateLimitUpdatedAt(); ok {
		_spec.SetField(agentprovider.FieldCliRateLimitUpdatedAt, field.TypeTime, value)
		_node.CliRateLimitUpdatedAt = &value
	}
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(agentprovider.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.ModelTemperature(); ok {
		_spec.SetField(agentprovider.FieldModelTemperature, field.TypeFloat64, value)
		_node.ModelTemperature = value
	}
	if value, ok := _c.mutation.ModelMaxTokens(); ok {
		_spec.SetField(agentprovider.FieldModelMaxTokens, field.TypeInt, value)
		_node.ModelMaxTokens = value
	}
	if value, ok := _c.mutation.MaxParallelRuns(); ok {
		_spec.SetField(agentprovider.FieldMaxParallelRuns, field.TypeInt, value)
		_node.MaxParallelRuns = value
	}
	if value, ok := _c.mutation.CostPerInputToken(); ok {
		_spec.SetField(agentprovider.FieldCostPerInputToken, field.TypeFloat64, value)
		_node.CostPerInputToken = value
	}
	if value, ok := _c.mutation.CostPerOutputToken(); ok {
		_spec.SetField(agentprovider.FieldCostPerOutputToken, field.TypeFloat64, value)
		_node.CostPerOutputToken = value
	}
	if value, ok := _c.mutation.PricingConfig(); ok {
		_spec.SetField(agentprovider.FieldPricingConfig, field.TypeJSON, value)
		_node.PricingConfig = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentprovider.OrganizationTable,
			Columns: []string{agentprovider.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MachineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentprovider.MachineTable,
			Columns: []string{agentprovider.MachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MachineID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentprovider.AgentsTable,
			Columns: []string{agentprovider.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentprovider.AgentRunsTable,
			Columns: []string{agentprovider.AgentRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentProviderCreateBulk is the builder for creating many AgentProvider entities in bulk.
type AgentProviderCreateBulk struct {
	config
	err      error
	builders []*AgentProviderCreate
}

// Save creates the AgentProvider entities in the database.
func (_c *AgentProviderCreateBulk) Save(ctx context.Context) ([]*AgentProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentProviderCreateBulk) SaveX(ctx context.Context) []*AgentProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
