// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/authauditevent"
	"github.com/BetterAndBetterII/openase/ent/predicate"
	"github.com/google/uuid"
)

// AuthAuditEventUpdate is the builder for updating AuthAuditEvent entities.
type AuthAuditEventUpdate struct {
	config
	hooks    []Hook
	mutation *AuthAuditEventMutation
}

// Where appends a list predicates to the AuthAuditEventUpdate builder.
func (_u *AuthAuditEventUpdate) Where(ps ...predicate.AuthAuditEvent) *AuthAuditEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthAuditEventUpdate) SetUserID(v uuid.UUID) *AuthAuditEventUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthAuditEventUpdate) SetNillableUserID(v *uuid.UUID) *AuthAuditEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AuthAuditEventUpdate) ClearUserID() *AuthAuditEventUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AuthAuditEventUpdate) SetSessionID(v uuid.UUID) *AuthAuditEventUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AuthAuditEventUpdate) SetNillableSessionID(v *uuid.UUID) *AuthAuditEventUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *AuthAuditEventUpdate) ClearSessionID() *AuthAuditEventUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *AuthAuditEventUpdate) SetActorID(v string) *AuthAuditEventUpdate {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *AuthAuditEventUpdate) SetNillableActorID(v *string) *AuthAuditEventUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *AuthAuditEventUpdate) SetEventType(v string) *AuthAuditEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *AuthAuditEventUpdate) SetNillableEventType(v *string) *AuthAuditEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *AuthAuditEventUpdate) SetMessage(v string) *AuthAuditEventUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *AuthAuditEventUpdate) SetNillableMessage(v *string) *AuthAuditEventUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AuthAuditEventUpdate) SetMetadata(v map[string]interface{}) *AuthAuditEventUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// Mutation returns the AuthAuditEventMutation object of the builder.
func (_u *AuthAuditEventUpdate) Mutation() *AuthAuditEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthAuditEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthAuditEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthAuditEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthAuditEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthAuditEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := authauditevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AuthAuditEvent.event_type": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthAuditEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authauditevent.Table, authauditevent.Columns, sqlgraph.NewFieldSpec(authauditevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authauditevent.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(authauditevent.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(authauditevent.FieldSessionID, field.TypeUUID, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(authauditevent.FieldSessionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(authauditevent.FieldActorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(authauditevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(authauditevent.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(authauditevent.FieldMetadata, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authauditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthAuditEventUpdateOne is the builder for updating a single AuthAuditEvent entity.
type AuthAuditEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthAuditEventMutation
}

// SetUserID sets the "user_id" field.
func (_u *AuthAuditEventUpdateOne) SetUserID(v uuid.UUID) *AuthAuditEventUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthAuditEventUpdateOne) SetNillableUserID(v *uuid.UUID) *AuthAuditEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AuthAuditEventUpdateOne) ClearUserID() *AuthAuditEventUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AuthAuditEventUpdateOne) SetSessionID(v uuid.UUID) *AuthAuditEventUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AuthAuditEventUpdateOne) SetNillableSessionID(v *uuid.UUID) *AuthAuditEventUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *AuthAuditEventUpdateOne) ClearSessionID() *AuthAuditEventUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *AuthAuditEventUpdateOne) SetActorID(v string) *AuthAuditEventUpdateOne {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *AuthAuditEventUpdateOne) SetNillableActorID(v *string) *AuthAuditEventUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *AuthAuditEventUpdateOne) SetEventType(v string) *AuthAuditEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *AuthAuditEventUpdateOne) SetNillableEventType(v *string) *AuthAuditEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *AuthAuditEventUpdateOne) SetMessage(v string) *AuthAuditEventUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *AuthAuditEventUpdateOne) SetNillableMessage(v *string) *AuthAuditEventUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AuthAuditEventUpdateOne) SetMetadata(v map[string]interface{}) *AuthAuditEventUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// Mutation returns the AuthAuditEventMutation object of the builder.
func (_u *AuthAuditEventUpdateOne) Mutation() *AuthAuditEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthAuditEventUpdate builder.
func (_u *AuthAuditEventUpdateOne) Where(ps ...predicate.AuthAuditEvent) *AuthAuditEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthAuditEventUpdateOne) Select(field string, fields ...string) *AuthAuditEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthAuditEvent entity.
func (_u *AuthAuditEventUpdateOne) Save(ctx context.Context) (*AuthAuditEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthAuditEventUpdateOne) SaveX(ctx context.Context) *AuthAuditEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthAuditEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthAuditEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthAuditEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := authauditevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AuthAuditEvent.event_type": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthAuditEventUpdateOne) sqlSave(ctx context.Context) (_node *AuthAuditEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authauditevent.Table, authauditevent.Columns, sqlgraph.NewFieldSpec(authauditevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthAuditEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authauditevent.FieldID)
		for _, f := range fields {
			if !authauditevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authauditevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authauditevent.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(authauditevent.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(authauditevent.FieldSessionID, field.TypeUUID, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(authauditevent.FieldSessionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(authauditevent.FieldActorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(authauditevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(authauditevent.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(authauditevent.FieldMetadata, field.TypeJSON, value)
	}
	_node = &AuthAuditEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authauditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
