// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/chatconversation"
	"github.com/BetterAndBetterII/openase/ent/chatentry"
	"github.com/BetterAndBetterII/openase/ent/chatturn"
	"github.com/BetterAndBetterII/openase/ent/predicate"
	"github.com/google/uuid"
)

// ChatEntryQuery is the builder for querying ChatEntry entities.
type ChatEntryQuery struct {
	config
	ctx              *QueryContext
	order            []chatentry.OrderOption
	inters           []Interceptor
	predicates       []predicate.ChatEntry
	withConversation *ChatConversationQuery
	withTurn         *ChatTurnQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatEntryQuery builder.
func (_q *ChatEntryQuery) Where(ps ...predicate.ChatEntry) *ChatEntryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChatEntryQuery) Limit(limit int) *ChatEntryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChatEntryQuery) Offset(offset int) *ChatEntryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChatEntryQuery) Unique(unique bool) *ChatEntryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChatEntryQuery) Order(o ...chatentry.OrderOption) *ChatEntryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryConversation chains the current query on the "conversation" edge.
func (_q *ChatEntryQuery) QueryConversation() *ChatConversationQuery {
	query := (&ChatConversationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatentry.Table, chatentry.FieldID, selector),
			sqlgraph.To(chatconversation.Table, chatconversation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chatentry.ConversationTable, chatentry.ConversationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTurn chains the current query on the "turn" edge.
func (_q *ChatEntryQuery) QueryTurn() *ChatTurnQuery {
	query := (&ChatTurnClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatentry.Table, chatentry.FieldID, selector),
			sqlgraph.To(chatturn.Table, chatturn.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chatentry.TurnTable, chatentry.TurnColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChatEntry entity from the query.
// Returns a *NotFoundError when no ChatEntry was found.
func (_q *ChatEntryQuery) First(ctx context.Context) (*ChatEntry, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatentry.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChatEntryQuery) FirstX(ctx context.Context) *ChatEntry {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatEntry ID from the query.
// Returns a *NotFoundError when no ChatEntry ID was found.
func (_q *ChatEntryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chatentry.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChatEntryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatEntry entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatEntry entity is found.
// Returns a *NotFoundError when no ChatEntry entities are found.
func (_q *ChatEntryQuery) Only(ctx context.Context) (*ChatEntry, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatentry.Label}
	default:
		return nil, &NotSingularError{chatentry.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChatEntryQuery) OnlyX(ctx context.Context) *ChatEntry {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatEntry ID in the query.
// Returns a *NotSingularError when more than one ChatEntry ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChatEntryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chatentry.Label}
	default:
		err = &NotSingularError{chatentry.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChatEntryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatEntries.
func (_q *ChatEntryQuery) All(ctx context.Context) ([]*ChatEntry, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatEntry, *ChatEntryQuery]()
	return withInterceptors[[]*ChatEntry](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChatEntryQuery) AllX(ctx context.Context) []*ChatEntry {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatEntry IDs.
func (_q *ChatEntryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(chatentry.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChatEntryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChatEntryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChatEntryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChatEntryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChatEntryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChatEntryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatEntryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChatEntryQuery) Clone() *ChatEntryQuery {
	if _q == nil {
		return nil
	}
	return &ChatEntryQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]chatentry.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.ChatEntry{}, _q.predicates...),
		withConversation: _q.withConversation.Clone(),
		withTurn:         _q.withTurn.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithConversation tells the query-builder to eager-load the nodes that are connected to
// the "conversation" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatEntryQuery) WithConversation(opts ...func(*ChatConversationQuery)) *ChatEntryQuery {
	query := (&ChatConversationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withConversation = query
	return _q
}

// WithTurn tells the query-builder to eager-load the nodes that are connected to
// the "turn" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatEntryQuery) WithTurn(opts ...func(*ChatTurnQuery)) *ChatEntryQuery {
	query := (&ChatTurnClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTurn = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ConversationID uuid.UUID `json:"conversation_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatEntry.Query().
//		GroupBy(chatentry.FieldConversationID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChatEntryQuery) GroupBy(field string, fields ...string) *ChatEntryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatEntryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = chatentry.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ConversationID uuid.UUID `json:"conversation_id,omitempty"`
//	}
//
//	client.ChatEntry.Query().
//		Select(chatentry.FieldConversationID).
//		Scan(ctx, &v)
func (_q *ChatEntryQuery) Select(fields ...string) *ChatEntrySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChatEntrySelect{ChatEntryQuery: _q}
	sbuild.label = chatentry.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatEntrySelect configured with the given aggregations.
func (_q *ChatEntryQuery) Aggregate(fns ...AggregateFunc) *ChatEntrySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChatEntryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !chatentry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChatEntryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatEntry, error) {
	var (
		nodes       = []*ChatEntry{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withConversation != nil,
			_q.withTurn != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatEntry).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatEntry{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withConversation; query != nil {
		if err := _q.loadConversation(ctx, query, nodes, nil,
			func(n *ChatEntry, e *ChatConversation) { n.Edges.Conversation = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTurn; query != nil {
		if err := _q.loadTurn(ctx, query, nodes, nil,
			func(n *ChatEntry, e *ChatTurn) { n.Edges.Turn = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChatEntryQuery) loadConversation(ctx context.Context, query *ChatConversationQuery, nodes []*ChatEntry, init func(*ChatEntry), assign func(*ChatEntry, *ChatConversation)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ChatEntry)
	for i := range nodes {
		fk := nodes[i].ConversationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chatconversation.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "conversation_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChatEntryQuery) loadTurn(ctx context.Context, query *ChatTurnQuery, nodes []*ChatEntry, init func(*ChatEntry), assign func(*ChatEntry, *ChatTurn)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ChatEntry)
	for i := range nodes {
		if nodes[i].TurnID == nil {
			continue
		}
		fk := *nodes[i].TurnID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chatturn.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "turn_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ChatEntryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChatEntryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatentry.Table, chatentry.Columns, sqlgraph.NewFieldSpec(chatentry.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatentry.FieldID)
		for i := range fields {
			if fields[i] != chatentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withConversation != nil {
			_spec.Node.AddColumnOnce(chatentry.FieldConversationID)
		}
		if _q.withTurn != nil {
			_spec.Node.AddColumnOnce(chatentry.FieldTurnID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChatEntryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(chatentry.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = chatentry.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChatEntryGroupBy is the group-by builder for ChatEntry entities.
type ChatEntryGroupBy struct {
	selector
	build *ChatEntryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChatEntryGroupBy) Aggregate(fns ...AggregateFunc) *ChatEntryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChatEntryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatEntryQuery, *ChatEntryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChatEntryGroupBy) sqlScan(ctx context.Context, root *ChatEntryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatEntrySelect is the builder for selecting fields of ChatEntry entities.
type ChatEntrySelect struct {
	*ChatEntryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChatEntrySelect) Aggregate(fns ...AggregateFunc) *ChatEntrySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChatEntrySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatEntryQuery, *ChatEntrySelect](ctx, _s.ChatEntryQuery, _s, _s.inters, v)
}

func (_s *ChatEntrySelect) sqlScan(ctx context.Context, root *ChatEntryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
