// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/BetterAndBetterII/openase/ent/organization"
	"github.com/BetterAndBetterII/openase/ent/organizationdailytokenusage"
	"github.com/google/uuid"
)

// OrganizationDailyTokenUsage is the model entity for the OrganizationDailyTokenUsage schema.
type OrganizationDailyTokenUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID uuid.UUID `json:"organization_id,omitempty"`
	// UsageDate holds the value of the "usage_date" field.
	UsageDate time.Time `json:"usage_date,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// CachedInputTokens holds the value of the "cached_input_tokens" field.
	CachedInputTokens int64 `json:"cached_input_tokens,omitempty"`
	// ReasoningTokens holds the value of the "reasoning_tokens" field.
	ReasoningTokens int64 `json:"reasoning_tokens,omitempty"`
	// TotalTokens holds the value of the "total_tokens" field.
	TotalTokens int64 `json:"total_tokens,omitempty"`
	// FinalizedRunCount holds the value of the "finalized_run_count" field.
	FinalizedRunCount int `json:"finalized_run_count,omitempty"`
	// RecomputedAt holds the value of the "recomputed_at" field.
	RecomputedAt time.Time `json:"recomputed_at,omitempty"`
	// SourceMode holds the value of the "source_mode" field.
	SourceMode organizationdailytokenusage.SourceMode `json:"source_mode,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrganizationDailyTokenUsageQuery when eager-loading is set.
	Edges        OrganizationDailyTokenUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrganizationDailyTokenUsageEdges holds the relations/edges for other nodes in the graph.
type OrganizationDailyTokenUsageEdges struct {
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationDailyTokenUsageEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrganizationDailyTokenUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case organizationdailytokenusage.FieldInputTokens, organizationdailytokenusage.FieldOutputTokens, organizationdailytokenusage.FieldCachedInputTokens, organizationdailytokenusage.FieldReasoningTokens, organizationdailytokenusage.FieldTotalTokens, organizationdailytokenusage.FieldFinalizedRunCount:
			values[i] = new(sql.NullInt64)
		case organizationdailytokenusage.FieldSourceMode:
			values[i] = new(sql.NullString)
		case organizationdailytokenusage.FieldUsageDate, organizationdailytokenusage.FieldRecomputedAt:
			values[i] = new(sql.NullTime)
		case organizationdailytokenusage.FieldID, organizationdailytokenusage.FieldOrganizationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrganizationDailyTokenUsage fields.
func (_m *OrganizationDailyTokenUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case organizationdailytokenusage.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case organizationdailytokenusage.FieldOrganizationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value != nil {
				_m.OrganizationID = *value
			}
		case organizationdailytokenusage.FieldUsageDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field usage_date", values[i])
			} else if value.Valid {
				_m.UsageDate = value.Time
			}
		case organizationdailytokenusage.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case organizationdailytokenusage.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = value.Int64
			}
		case organizationdailytokenusage.FieldCachedInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_input_tokens", values[i])
			} else if value.Valid {
				_m.CachedInputTokens = value.Int64
			}
		case organizationdailytokenusage.FieldReasoningTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_tokens", values[i])
			} else if value.Valid {
				_m.ReasoningTokens = value.Int64
			}
		case organizationdailytokenusage.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = value.Int64
			}
		case organizationdailytokenusage.FieldFinalizedRunCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field finalized_run_count", values[i])
			} else if value.Valid {
				_m.FinalizedRunCount = int(value.Int64)
			}
		case organizationdailytokenusage.FieldRecomputedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recomputed_at", values[i])
			} else if value.Valid {
				_m.RecomputedAt = value.Time
			}
		case organizationdailytokenusage.FieldSourceMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_mode", values[i])
			} else if value.Valid {
				_m.SourceMode = organizationdailytokenusage.SourceMode(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrganizationDailyTokenUsage.
// This includes values selected through modifiers, order, etc.
func (_m *OrganizationDailyTokenUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrganization queries the "organization" edge of the OrganizationDailyTokenUsage entity.
func (_m *OrganizationDailyTokenUsage) QueryOrganization() *OrganizationQuery {
	return NewOrganizationDailyTokenUsageClient(_m.config).QueryOrganization(_m)
}

// Update returns a builder for updating this OrganizationDailyTokenUsage.
// Note that you need to call OrganizationDailyTokenUsage.Unwrap() before calling this method if this OrganizationDailyTokenUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrganizationDailyTokenUsage) Update() *OrganizationDailyTokenUsageUpdateOne {
	return NewOrganizationDailyTokenUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrganizationDailyTokenUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrganizationDailyTokenUsage) Unwrap() *OrganizationDailyTokenUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrganizationDailyTokenUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrganizationDailyTokenUsage) String() string {
	var builder strings.Builder
	builder.WriteString("OrganizationDailyTokenUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("usage_date=")
	builder.WriteString(_m.UsageDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cached_input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CachedInputTokens))
	builder.WriteString(", ")
	builder.WriteString("reasoning_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReasoningTokens))
	builder.WriteString(", ")
	builder.WriteString("total_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokens))
	builder.WriteString(", ")
	builder.WriteString("finalized_run_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FinalizedRunCount))
	builder.WriteString(", ")
	builder.WriteString("recomputed_at=")
	builder.WriteString(_m.RecomputedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceMode))
	builder.WriteByte(')')
	return builder.String()
}

// OrganizationDailyTokenUsages is a parsable slice of OrganizationDailyTokenUsage.
type OrganizationDailyTokenUsages []*OrganizationDailyTokenUsage
