// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/project"
	"github.com/BetterAndBetterII/openase/ent/projectupdatecomment"
	"github.com/BetterAndBetterII/openase/ent/projectupdatethread"
	"github.com/BetterAndBetterII/openase/ent/projectupdatethreadrevision"
	"github.com/google/uuid"
)

// ProjectUpdateThreadCreate is the builder for creating a ProjectUpdateThread entity.
type ProjectUpdateThreadCreate struct {
	config
	mutation *ProjectUpdateThreadMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *ProjectUpdateThreadCreate) SetProjectID(v uuid.UUID) *ProjectUpdateThreadCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProjectUpdateThreadCreate) SetStatus(v projectupdatethread.Status) *ProjectUpdateThreadCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ProjectUpdateThreadCreate) SetTitle(v string) *ProjectUpdateThreadCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetBodyMarkdown sets the "body_markdown" field.
func (_c *ProjectUpdateThreadCreate) SetBodyMarkdown(v string) *ProjectUpdateThreadCreate {
	_c.mutation.SetBodyMarkdown(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ProjectUpdateThreadCreate) SetCreatedBy(v string) *ProjectUpdateThreadCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectUpdateThreadCreate) SetCreatedAt(v time.Time) *ProjectUpdateThreadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableCreatedAt(v *time.Time) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProjectUpdateThreadCreate) SetUpdatedAt(v time.Time) *ProjectUpdateThreadCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableUpdatedAt(v *time.Time) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEditedAt sets the "edited_at" field.
func (_c *ProjectUpdateThreadCreate) SetEditedAt(v time.Time) *ProjectUpdateThreadCreate {
	_c.mutation.SetEditedAt(v)
	return _c
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableEditedAt(v *time.Time) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetEditedAt(*v)
	}
	return _c
}

// SetEditCount sets the "edit_count" field.
func (_c *ProjectUpdateThreadCreate) SetEditCount(v int) *ProjectUpdateThreadCreate {
	_c.mutation.SetEditCount(v)
	return _c
}

// SetNillableEditCount sets the "edit_count" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableEditCount(v *int) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetEditCount(*v)
	}
	return _c
}

// SetLastEditedBy sets the "last_edited_by" field.
func (_c *ProjectUpdateThreadCreate) SetLastEditedBy(v string) *ProjectUpdateThreadCreate {
	_c.mutation.SetLastEditedBy(v)
	return _c
}

// SetNillableLastEditedBy sets the "last_edited_by" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableLastEditedBy(v *string) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetLastEditedBy(*v)
	}
	return _c
}

// SetIsDeleted sets the "is_deleted" field.
func (_c *ProjectUpdateThreadCreate) SetIsDeleted(v bool) *ProjectUpdateThreadCreate {
	_c.mutation.SetIsDeleted(v)
	return _c
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableIsDeleted(v *bool) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetIsDeleted(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ProjectUpdateThreadCreate) SetDeletedAt(v time.Time) *ProjectUpdateThreadCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableDeletedAt(v *time.Time) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *ProjectUpdateThreadCreate) SetDeletedBy(v string) *ProjectUpdateThreadCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableDeletedBy(v *string) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_c *ProjectUpdateThreadCreate) SetLastActivityAt(v time.Time) *ProjectUpdateThreadCreate {
	_c.mutation.SetLastActivityAt(v)
	return _c
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableLastActivityAt(v *time.Time) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetLastActivityAt(*v)
	}
	return _c
}

// SetCommentCount sets the "comment_count" field.
func (_c *ProjectUpdateThreadCreate) SetCommentCount(v int) *ProjectUpdateThreadCreate {
	_c.mutation.SetCommentCount(v)
	return _c
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableCommentCount(v *int) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetCommentCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectUpdateThreadCreate) SetID(v uuid.UUID) *ProjectUpdateThreadCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProjectUpdateThreadCreate) SetNillableID(v *uuid.UUID) *ProjectUpdateThreadCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ProjectUpdateThreadCreate) SetProject(v *Project) *ProjectUpdateThreadCreate {
	return _c.SetProjectID(v.ID)
}

// AddRevisionIDs adds the "revisions" edge to the ProjectUpdateThreadRevision entity by IDs.
func (_c *ProjectUpdateThreadCreate) AddRevisionIDs(ids ...uuid.UUID) *ProjectUpdateThreadCreate {
	_c.mutation.AddRevisionIDs(ids...)
	return _c
}

// AddRevisions adds the "revisions" edges to the ProjectUpdateThreadRevision entity.
func (_c *ProjectUpdateThreadCreate) AddRevisions(v ...*ProjectUpdateThreadRevision) *ProjectUpdateThreadCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRevisionIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the ProjectUpdateComment entity by IDs.
func (_c *ProjectUpdateThreadCreate) AddCommentIDs(ids ...uuid.UUID) *ProjectUpdateThreadCreate {
	_c.mutation.AddCommentIDs(ids...)
	return _c
}

// AddComments adds the "comments" edges to the ProjectUpdateComment entity.
func (_c *ProjectUpdateThreadCreate) AddComments(v ...*ProjectUpdateComment) *ProjectUpdateThreadCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommentIDs(ids...)
}

// Mutation returns the ProjectUpdateThreadMutation object of the builder.
func (_c *ProjectUpdateThreadCreate) Mutation() *ProjectUpdateThreadMutation {
	return _c.mutation
}

// Save creates the ProjectUpdateThread in the database.
func (_c *ProjectUpdateThreadCreate) Save(ctx context.Context) (*ProjectUpdateThread, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectUpdateThreadCreate) SaveX(ctx context.Context) *ProjectUpdateThread {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectUpdateThreadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectUpdateThreadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectUpdateThreadCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projectupdatethread.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := projectupdatethread.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EditCount(); !ok {
		v := projectupdatethread.DefaultEditCount
		_c.mutation.SetEditCount(v)
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		v := projectupdatethread.DefaultIsDeleted
		_c.mutation.SetIsDeleted(v)
	}
	if _, ok := _c.mutation.LastActivityAt(); !ok {
		v := projectupdatethread.DefaultLastActivityAt()
		_c.mutation.SetLastActivityAt(v)
	}
	if _, ok := _c.mutation.CommentCount(); !ok {
		v := projectupdatethread.DefaultCommentCount
		_c.mutation.SetCommentCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := projectupdatethread.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectUpdateThreadCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ProjectUpdateThread.project_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProjectUpdateThread.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := projectupdatethread.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProjectUpdateThread.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ProjectUpdateThread.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := projectupdatethread.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ProjectUpdateThread.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BodyMarkdown(); !ok {
		return &ValidationError{Name: "body_markdown", err: errors.New(`ent: missing required field "ProjectUpdateThread.body_markdown"`)}
	}
	if v, ok := _c.mutation.BodyMarkdown(); ok {
		if err := projectupdatethread.BodyMarkdownValidator(v); err != nil {
			return &ValidationError{Name: "body_markdown", err: fmt.Errorf(`ent: validator failed for field "ProjectUpdateThread.body_markdown": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ProjectUpdateThread.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := projectupdatethread.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "ProjectUpdateThread.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectUpdateThread.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProjectUpdateThread.updated_at"`)}
	}
	if _, ok := _c.mutation.EditCount(); !ok {
		return &ValidationError{Name: "edit_count", err: errors.New(`ent: missing required field "ProjectUpdateThread.edit_count"`)}
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "ProjectUpdateThread.is_deleted"`)}
	}
	if _, ok := _c.mutation.LastActivityAt(); !ok {
		return &ValidationError{Name: "last_activity_at", err: errors.New(`ent: missing required field "ProjectUpdateThread.last_activity_at"`)}
	}
	if _, ok := _c.mutation.CommentCount(); !ok {
		return &ValidationError{Name: "comment_count", err: errors.New(`ent: missing required field "ProjectUpdateThread.comment_count"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ProjectUpdateThread.project"`)}
	}
	return nil
}

func (_c *ProjectUpdateThreadCreate) sqlSave(ctx context.Context) (*ProjectUpdateThread, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectUpdateThreadCreate) createSpec() (*ProjectUpdateThread, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectUpdateThread{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectupdatethread.Table, sqlgraph.NewFieldSpec(projectupdatethread.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(projectupdatethread.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(projectupdatethread.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.BodyMarkdown(); ok {
		_spec.SetField(projectupdatethread.FieldBodyMarkdown, field.TypeString, value)
		_node.BodyMarkdown = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(projectupdatethread.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projectupdatethread.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(projectupdatethread.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.EditedAt(); ok {
		_spec.SetField(projectupdatethread.FieldEditedAt, field.TypeTime, value)
		_node.EditedAt = &value
	}
	if value, ok := _c.mutation.EditCount(); ok {
		_spec.SetField(projectupdatethread.FieldEditCount, field.TypeInt, value)
		_node.EditCount = value
	}
	if value, ok := _c.mutation.LastEditedBy(); ok {
		_spec.SetField(projectupdatethread.FieldLastEditedBy, field.TypeString, value)
		_node.LastEditedBy = &value
	}
	if value, ok := _c.mutation.IsDeleted(); ok {
		_spec.SetField(projectupdatethread.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(projectupdatethread.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(projectupdatethread.FieldDeletedBy, field.TypeString, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.LastActivityAt(); ok {
		_spec.SetField(projectupdatethread.FieldLastActivityAt, field.TypeTime, value)
		_node.LastActivityAt = value
	}
	if value, ok := _c.mutation.CommentCount(); ok {
		_spec.SetField(projectupdatethread.FieldCommentCount, field.TypeInt, value)
		_node.CommentCount = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectupdatethread.ProjectTable,
			Columns: []string{projectupdatethread.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RevisionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectupdatethread.RevisionsTable,
			Columns: []string{projectupdatethread.RevisionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectupdatethreadrevision.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectupdatethread.CommentsTable,
			Columns: []string{projectupdatethread.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectupdatecomment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectUpdateThreadCreateBulk is the builder for creating many ProjectUpdateThread entities in bulk.
type ProjectUpdateThreadCreateBulk struct {
	config
	err      error
	builders []*ProjectUpdateThreadCreate
}

// Save creates the ProjectUpdateThread entities in the database.
func (_c *ProjectUpdateThreadCreateBulk) Save(ctx context.Context) ([]*ProjectUpdateThread, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectUpdateThread, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectUpdateThreadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectUpdateThreadCreateBulk) SaveX(ctx context.Context) []*ProjectUpdateThread {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectUpdateThreadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectUpdateThreadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
