// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/project"
	"github.com/BetterAndBetterII/openase/ent/projectrepo"
	"github.com/BetterAndBetterII/openase/ent/ticketreposcope"
	"github.com/BetterAndBetterII/openase/ent/ticketrepoworkspace"
	"github.com/BetterAndBetterII/openase/internal/types/pgarray"
	"github.com/google/uuid"
)

// ProjectRepoCreate is the builder for creating a ProjectRepo entity.
type ProjectRepoCreate struct {
	config
	mutation *ProjectRepoMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *ProjectRepoCreate) SetProjectID(v uuid.UUID) *ProjectRepoCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ProjectRepoCreate) SetName(v string) *ProjectRepoCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRepositoryURL sets the "repository_url" field.
func (_c *ProjectRepoCreate) SetRepositoryURL(v string) *ProjectRepoCreate {
	_c.mutation.SetRepositoryURL(v)
	return _c
}

// SetDefaultBranch sets the "default_branch" field.
func (_c *ProjectRepoCreate) SetDefaultBranch(v string) *ProjectRepoCreate {
	_c.mutation.SetDefaultBranch(v)
	return _c
}

// SetNillableDefaultBranch sets the "default_branch" field if the given value is not nil.
func (_c *ProjectRepoCreate) SetNillableDefaultBranch(v *string) *ProjectRepoCreate {
	if v != nil {
		_c.SetDefaultBranch(*v)
	}
	return _c
}

// SetWorkspaceDirname sets the "workspace_dirname" field.
func (_c *ProjectRepoCreate) SetWorkspaceDirname(v string) *ProjectRepoCreate {
	_c.mutation.SetWorkspaceDirname(v)
	return _c
}

// SetNillableWorkspaceDirname sets the "workspace_dirname" field if the given value is not nil.
func (_c *ProjectRepoCreate) SetNillableWorkspaceDirname(v *string) *ProjectRepoCreate {
	if v != nil {
		_c.SetWorkspaceDirname(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *ProjectRepoCreate) SetLabels(v pgarray.StringArray) *ProjectRepoCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectRepoCreate) SetID(v uuid.UUID) *ProjectRepoCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProjectRepoCreate) SetNillableID(v *uuid.UUID) *ProjectRepoCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ProjectRepoCreate) SetProject(v *Project) *ProjectRepoCreate {
	return _c.SetProjectID(v.ID)
}

// AddTicketScopeIDs adds the "ticket_scopes" edge to the TicketRepoScope entity by IDs.
func (_c *ProjectRepoCreate) AddTicketScopeIDs(ids ...uuid.UUID) *ProjectRepoCreate {
	_c.mutation.AddTicketScopeIDs(ids...)
	return _c
}

// AddTicketScopes adds the "ticket_scopes" edges to the TicketRepoScope entity.
func (_c *ProjectRepoCreate) AddTicketScopes(v ...*TicketRepoScope) *ProjectRepoCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketScopeIDs(ids...)
}

// AddTicketRepoWorkspaceIDs adds the "ticket_repo_workspaces" edge to the TicketRepoWorkspace entity by IDs.
func (_c *ProjectRepoCreate) AddTicketRepoWorkspaceIDs(ids ...uuid.UUID) *ProjectRepoCreate {
	_c.mutation.AddTicketRepoWorkspaceIDs(ids...)
	return _c
}

// AddTicketRepoWorkspaces adds the "ticket_repo_workspaces" edges to the TicketRepoWorkspace entity.
func (_c *ProjectRepoCreate) AddTicketRepoWorkspaces(v ...*TicketRepoWorkspace) *ProjectRepoCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketRepoWorkspaceIDs(ids...)
}

// Mutation returns the ProjectRepoMutation object of the builder.
func (_c *ProjectRepoCreate) Mutation() *ProjectRepoMutation {
	return _c.mutation
}

// Save creates the ProjectRepo in the database.
func (_c *ProjectRepoCreate) Save(ctx context.Context) (*ProjectRepo, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectRepoCreate) SaveX(ctx context.Context) *ProjectRepo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectRepoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectRepoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectRepoCreate) defaults() {
	if _, ok := _c.mutation.DefaultBranch(); !ok {
		v := projectrepo.DefaultDefaultBranch
		_c.mutation.SetDefaultBranch(v)
	}
	if _, ok := _c.mutation.WorkspaceDirname(); !ok {
		v := projectrepo.DefaultWorkspaceDirname
		_c.mutation.SetWorkspaceDirname(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := projectrepo.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectRepoCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ProjectRepo.project_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProjectRepo.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := projectrepo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProjectRepo.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RepositoryURL(); !ok {
		return &ValidationError{Name: "repository_url", err: errors.New(`ent: missing required field "ProjectRepo.repository_url"`)}
	}
	if v, ok := _c.mutation.RepositoryURL(); ok {
		if err := projectrepo.RepositoryURLValidator(v); err != nil {
			return &ValidationError{Name: "repository_url", err: fmt.Errorf(`ent: validator failed for field "ProjectRepo.repository_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultBranch(); !ok {
		return &ValidationError{Name: "default_branch", err: errors.New(`ent: missing required field "ProjectRepo.default_branch"`)}
	}
	if _, ok := _c.mutation.WorkspaceDirname(); !ok {
		return &ValidationError{Name: "workspace_dirname", err: errors.New(`ent: missing required field "ProjectRepo.workspace_dirname"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ProjectRepo.project"`)}
	}
	return nil
}

func (_c *ProjectRepoCreate) sqlSave(ctx context.Context) (*ProjectRepo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectRepoCreate) createSpec() (*ProjectRepo, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectRepo{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectrepo.Table, sqlgraph.NewFieldSpec(projectrepo.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(projectrepo.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.RepositoryURL(); ok {
		_spec.SetField(projectrepo.FieldRepositoryURL, field.TypeString, value)
		_node.RepositoryURL = value
	}
	if value, ok := _c.mutation.DefaultBranch(); ok {
		_spec.SetField(projectrepo.FieldDefaultBranch, field.TypeString, value)
		_node.DefaultBranch = value
	}
	if value, ok := _c.mutation.WorkspaceDirname(); ok {
		_spec.SetField(projectrepo.FieldWorkspaceDirname, field.TypeString, value)
		_node.WorkspaceDirname = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(projectrepo.FieldLabels, field.TypeOther, value)
		_node.Labels = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectrepo.ProjectTable,
			Columns: []string{projectrepo.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TicketScopesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectrepo.TicketScopesTable,
			Columns: []string{projectrepo.TicketScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketreposcope.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TicketRepoWorkspacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectrepo.TicketRepoWorkspacesTable,
			Columns: []string{projectrepo.TicketRepoWorkspacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketrepoworkspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectRepoCreateBulk is the builder for creating many ProjectRepo entities in bulk.
type ProjectRepoCreateBulk struct {
	config
	err      error
	builders []*ProjectRepoCreate
}

// Save creates the ProjectRepo entities in the database.
func (_c *ProjectRepoCreateBulk) Save(ctx context.Context) ([]*ProjectRepo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectRepo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectRepoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectRepoCreateBulk) SaveX(ctx context.Context) []*ProjectRepo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectRepoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectRepoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
