// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/projectupdatecomment"
	"github.com/BetterAndBetterII/openase/ent/projectupdatecommentrevision"
	"github.com/BetterAndBetterII/openase/ent/projectupdatethread"
	"github.com/google/uuid"
)

// ProjectUpdateCommentCreate is the builder for creating a ProjectUpdateComment entity.
type ProjectUpdateCommentCreate struct {
	config
	mutation *ProjectUpdateCommentMutation
	hooks    []Hook
}

// SetThreadID sets the "thread_id" field.
func (_c *ProjectUpdateCommentCreate) SetThreadID(v uuid.UUID) *ProjectUpdateCommentCreate {
	_c.mutation.SetThreadID(v)
	return _c
}

// SetBodyMarkdown sets the "body_markdown" field.
func (_c *ProjectUpdateCommentCreate) SetBodyMarkdown(v string) *ProjectUpdateCommentCreate {
	_c.mutation.SetBodyMarkdown(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ProjectUpdateCommentCreate) SetCreatedBy(v string) *ProjectUpdateCommentCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectUpdateCommentCreate) SetCreatedAt(v time.Time) *ProjectUpdateCommentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectUpdateCommentCreate) SetNillableCreatedAt(v *time.Time) *ProjectUpdateCommentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProjectUpdateCommentCreate) SetUpdatedAt(v time.Time) *ProjectUpdateCommentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProjectUpdateCommentCreate) SetNillableUpdatedAt(v *time.Time) *ProjectUpdateCommentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEditedAt sets the "edited_at" field.
func (_c *ProjectUpdateCommentCreate) SetEditedAt(v time.Time) *ProjectUpdateCommentCreate {
	_c.mutation.SetEditedAt(v)
	return _c
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_c *ProjectUpdateCommentCreate) SetNillableEditedAt(v *time.Time) *ProjectUpdateCommentCreate {
	if v != nil {
		_c.SetEditedAt(*v)
	}
	return _c
}

// SetEditCount sets the "edit_count" field.
func (_c *ProjectUpdateCommentCreate) SetEditCount(v int) *ProjectUpdateCommentCreate {
	_c.mutation.SetEditCount(v)
	return _c
}

// SetNillableEditCount sets the "edit_count" field if the given value is not nil.
func (_c *ProjectUpdateCommentCreate) SetNillableEditCount(v *int) *ProjectUpdateCommentCreate {
	if v != nil {
		_c.SetEditCount(*v)
	}
	return _c
}

// SetLastEditedBy sets the "last_edited_by" field.
func (_c *ProjectUpdateCommentCreate) SetLastEditedBy(v string) *ProjectUpdateCommentCreate {
	_c.mutation.SetLastEditedBy(v)
	return _c
}

// SetNillableLastEditedBy sets the "last_edited_by" field if the given value is not nil.
func (_c *ProjectUpdateCommentCreate) SetNillableLastEditedBy(v *string) *ProjectUpdateCommentCreate {
	if v != nil {
		_c.SetLastEditedBy(*v)
	}
	return _c
}

// SetIsDeleted sets the "is_deleted" field.
func (_c *ProjectUpdateCommentCreate) SetIsDeleted(v bool) *ProjectUpdateCommentCreate {
	_c.mutation.SetIsDeleted(v)
	return _c
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_c *ProjectUpdateCommentCreate) SetNillableIsDeleted(v *bool) *ProjectUpdateCommentCreate {
	if v != nil {
		_c.SetIsDeleted(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ProjectUpdateCommentCreate) SetDeletedAt(v time.Time) *ProjectUpdateCommentCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ProjectUpdateCommentCreate) SetNillableDeletedAt(v *time.Time) *ProjectUpdateCommentCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *ProjectUpdateCommentCreate) SetDeletedBy(v string) *ProjectUpdateCommentCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *ProjectUpdateCommentCreate) SetNillableDeletedBy(v *string) *ProjectUpdateCommentCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectUpdateCommentCreate) SetID(v uuid.UUID) *ProjectUpdateCommentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProjectUpdateCommentCreate) SetNillableID(v *uuid.UUID) *ProjectUpdateCommentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetThread sets the "thread" edge to the ProjectUpdateThread entity.
func (_c *ProjectUpdateCommentCreate) SetThread(v *ProjectUpdateThread) *ProjectUpdateCommentCreate {
	return _c.SetThreadID(v.ID)
}

// AddRevisionIDs adds the "revisions" edge to the ProjectUpdateCommentRevision entity by IDs.
func (_c *ProjectUpdateCommentCreate) AddRevisionIDs(ids ...uuid.UUID) *ProjectUpdateCommentCreate {
	_c.mutation.AddRevisionIDs(ids...)
	return _c
}

// AddRevisions adds the "revisions" edges to the ProjectUpdateCommentRevision entity.
func (_c *ProjectUpdateCommentCreate) AddRevisions(v ...*ProjectUpdateCommentRevision) *ProjectUpdateCommentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRevisionIDs(ids...)
}

// Mutation returns the ProjectUpdateCommentMutation object of the builder.
func (_c *ProjectUpdateCommentCreate) Mutation() *ProjectUpdateCommentMutation {
	return _c.mutation
}

// Save creates the ProjectUpdateComment in the database.
func (_c *ProjectUpdateCommentCreate) Save(ctx context.Context) (*ProjectUpdateComment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectUpdateCommentCreate) SaveX(ctx context.Context) *ProjectUpdateComment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectUpdateCommentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectUpdateCommentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectUpdateCommentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projectupdatecomment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := projectupdatecomment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EditCount(); !ok {
		v := projectupdatecomment.DefaultEditCount
		_c.mutation.SetEditCount(v)
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		v := projectupdatecomment.DefaultIsDeleted
		_c.mutation.SetIsDeleted(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := projectupdatecomment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectUpdateCommentCreate) check() error {
	if _, ok := _c.mutation.ThreadID(); !ok {
		return &ValidationError{Name: "thread_id", err: errors.New(`ent: missing required field "ProjectUpdateComment.thread_id"`)}
	}
	if _, ok := _c.mutation.BodyMarkdown(); !ok {
		return &ValidationError{Name: "body_markdown", err: errors.New(`ent: missing required field "ProjectUpdateComment.body_markdown"`)}
	}
	if v, ok := _c.mutation.BodyMarkdown(); ok {
		if err := projectupdatecomment.BodyMarkdownValidator(v); err != nil {
			return &ValidationError{Name: "body_markdown", err: fmt.Errorf(`ent: validator failed for field "ProjectUpdateComment.body_markdown": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ProjectUpdateComment.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := projectupdatecomment.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "ProjectUpdateComment.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectUpdateComment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProjectUpdateComment.updated_at"`)}
	}
	if _, ok := _c.mutation.EditCount(); !ok {
		return &ValidationError{Name: "edit_count", err: errors.New(`ent: missing required field "ProjectUpdateComment.edit_count"`)}
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "ProjectUpdateComment.is_deleted"`)}
	}
	if len(_c.mutation.ThreadIDs()) == 0 {
		return &ValidationError{Name: "thread", err: errors.New(`ent: missing required edge "ProjectUpdateComment.thread"`)}
	}
	return nil
}

func (_c *ProjectUpdateCommentCreate) sqlSave(ctx context.Context) (*ProjectUpdateComment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectUpdateCommentCreate) createSpec() (*ProjectUpdateComment, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectUpdateComment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectupdatecomment.Table, sqlgraph.NewFieldSpec(projectupdatecomment.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.BodyMarkdown(); ok {
		_spec.SetField(projectupdatecomment.FieldBodyMarkdown, field.TypeString, value)
		_node.BodyMarkdown = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(projectupdatecomment.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projectupdatecomment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(projectupdatecomment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.EditedAt(); ok {
		_spec.SetField(projectupdatecomment.FieldEditedAt, field.TypeTime, value)
		_node.EditedAt = &value
	}
	if value, ok := _c.mutation.EditCount(); ok {
		_spec.SetField(projectupdatecomment.FieldEditCount, field.TypeInt, value)
		_node.EditCount = value
	}
	if value, ok := _c.mutation.LastEditedBy(); ok {
		_spec.SetField(projectupdatecomment.FieldLastEditedBy, field.TypeString, value)
		_node.LastEditedBy = &value
	}
	if value, ok := _c.mutation.IsDeleted(); ok {
		_spec.SetField(projectupdatecomment.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(projectupdatecomment.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(projectupdatecomment.FieldDeletedBy, field.TypeString, value)
		_node.DeletedBy = &value
	}
	if nodes := _c.mutation.ThreadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectupdatecomment.ThreadTable,
			Columns: []string{projectupdatecomment.ThreadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectupdatethread.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ThreadID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RevisionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   projectupdatecomment.RevisionsTable,
			Columns: []string{projectupdatecomment.RevisionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectupdatecommentrevision.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectUpdateCommentCreateBulk is the builder for creating many ProjectUpdateComment entities in bulk.
type ProjectUpdateCommentCreateBulk struct {
	config
	err      error
	builders []*ProjectUpdateCommentCreate
}

// Save creates the ProjectUpdateComment entities in the database.
func (_c *ProjectUpdateCommentCreateBulk) Save(ctx context.Context) ([]*ProjectUpdateComment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectUpdateComment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectUpdateCommentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectUpdateCommentCreateBulk) SaveX(ctx context.Context) []*ProjectUpdateComment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectUpdateCommentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectUpdateCommentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
