// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/BetterAndBetterII/openase/ent/project"
	"github.com/BetterAndBetterII/openase/ent/projectrepo"
	"github.com/BetterAndBetterII/openase/internal/types/pgarray"
	"github.com/google/uuid"
)

// ProjectRepo is the model entity for the ProjectRepo schema.
type ProjectRepo struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// RepositoryURL holds the value of the "repository_url" field.
	RepositoryURL string `json:"repository_url,omitempty"`
	// DefaultBranch holds the value of the "default_branch" field.
	DefaultBranch string `json:"default_branch,omitempty"`
	// WorkspaceDirname holds the value of the "workspace_dirname" field.
	WorkspaceDirname string `json:"workspace_dirname,omitempty"`
	// Labels holds the value of the "labels" field.
	Labels pgarray.StringArray `json:"labels,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectRepoQuery when eager-loading is set.
	Edges        ProjectRepoEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectRepoEdges holds the relations/edges for other nodes in the graph.
type ProjectRepoEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// TicketScopes holds the value of the ticket_scopes edge.
	TicketScopes []*TicketRepoScope `json:"ticket_scopes,omitempty"`
	// TicketRepoWorkspaces holds the value of the ticket_repo_workspaces edge.
	TicketRepoWorkspaces []*TicketRepoWorkspace `json:"ticket_repo_workspaces,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectRepoEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// TicketScopesOrErr returns the TicketScopes value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectRepoEdges) TicketScopesOrErr() ([]*TicketRepoScope, error) {
	if e.loadedTypes[1] {
		return e.TicketScopes, nil
	}
	return nil, &NotLoadedError{edge: "ticket_scopes"}
}

// TicketRepoWorkspacesOrErr returns the TicketRepoWorkspaces value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectRepoEdges) TicketRepoWorkspacesOrErr() ([]*TicketRepoWorkspace, error) {
	if e.loadedTypes[2] {
		return e.TicketRepoWorkspaces, nil
	}
	return nil, &NotLoadedError{edge: "ticket_repo_workspaces"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectRepo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectrepo.FieldLabels:
			values[i] = new(pgarray.StringArray)
		case projectrepo.FieldName, projectrepo.FieldRepositoryURL, projectrepo.FieldDefaultBranch, projectrepo.FieldWorkspaceDirname:
			values[i] = new(sql.NullString)
		case projectrepo.FieldID, projectrepo.FieldProjectID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectRepo fields.
func (_m *ProjectRepo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectrepo.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case projectrepo.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case projectrepo.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case projectrepo.FieldRepositoryURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repository_url", values[i])
			} else if value.Valid {
				_m.RepositoryURL = value.String
			}
		case projectrepo.FieldDefaultBranch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_branch", values[i])
			} else if value.Valid {
				_m.DefaultBranch = value.String
			}
		case projectrepo.FieldWorkspaceDirname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_dirname", values[i])
			} else if value.Valid {
				_m.WorkspaceDirname = value.String
			}
		case projectrepo.FieldLabels:
			if value, ok := values[i].(*pgarray.StringArray); !ok {
				return fmt.Errorf("unexpected type %T for field labels", values[i])
			} else if value != nil {
				_m.Labels = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectRepo.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectRepo) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectRepo entity.
func (_m *ProjectRepo) QueryProject() *ProjectQuery {
	return NewProjectRepoClient(_m.config).QueryProject(_m)
}

// QueryTicketScopes queries the "ticket_scopes" edge of the ProjectRepo entity.
func (_m *ProjectRepo) QueryTicketScopes() *TicketRepoScopeQuery {
	return NewProjectRepoClient(_m.config).QueryTicketScopes(_m)
}

// QueryTicketRepoWorkspaces queries the "ticket_repo_workspaces" edge of the ProjectRepo entity.
func (_m *ProjectRepo) QueryTicketRepoWorkspaces() *TicketRepoWorkspaceQuery {
	return NewProjectRepoClient(_m.config).QueryTicketRepoWorkspaces(_m)
}

// Update returns a builder for updating this ProjectRepo.
// Note that you need to call ProjectRepo.Unwrap() before calling this method if this ProjectRepo
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectRepo) Update() *ProjectRepoUpdateOne {
	return NewProjectRepoClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectRepo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectRepo) Unwrap() *ProjectRepo {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectRepo is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectRepo) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectRepo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("repository_url=")
	builder.WriteString(_m.RepositoryURL)
	builder.WriteString(", ")
	builder.WriteString("default_branch=")
	builder.WriteString(_m.DefaultBranch)
	builder.WriteString(", ")
	builder.WriteString("workspace_dirname=")
	builder.WriteString(_m.WorkspaceDirname)
	builder.WriteString(", ")
	builder.WriteString("labels=")
	builder.WriteString(fmt.Sprintf("%v", _m.Labels))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectRepos is a parsable slice of ProjectRepo.
type ProjectRepos []*ProjectRepo
