// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/BetterAndBetterII/openase/ent/skillblob"
	"github.com/BetterAndBetterII/openase/ent/skillversion"
	"github.com/BetterAndBetterII/openase/ent/skillversionfile"
	"github.com/google/uuid"
)

// SkillVersionFile is the model entity for the SkillVersionFile schema.
type SkillVersionFile struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SkillVersionID holds the value of the "skill_version_id" field.
	SkillVersionID uuid.UUID `json:"skill_version_id,omitempty"`
	// ContentBlobID holds the value of the "content_blob_id" field.
	ContentBlobID uuid.UUID `json:"content_blob_id,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// FileKind holds the value of the "file_kind" field.
	FileKind skillversionfile.FileKind `json:"file_kind,omitempty"`
	// MediaType holds the value of the "media_type" field.
	MediaType string `json:"media_type,omitempty"`
	// Encoding holds the value of the "encoding" field.
	Encoding skillversionfile.Encoding `json:"encoding,omitempty"`
	// IsExecutable holds the value of the "is_executable" field.
	IsExecutable bool `json:"is_executable,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SkillVersionFileQuery when eager-loading is set.
	Edges        SkillVersionFileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SkillVersionFileEdges holds the relations/edges for other nodes in the graph.
type SkillVersionFileEdges struct {
	// SkillVersion holds the value of the skill_version edge.
	SkillVersion *SkillVersion `json:"skill_version,omitempty"`
	// ContentBlob holds the value of the content_blob edge.
	ContentBlob *SkillBlob `json:"content_blob,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SkillVersionOrErr returns the SkillVersion value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SkillVersionFileEdges) SkillVersionOrErr() (*SkillVersion, error) {
	if e.SkillVersion != nil {
		return e.SkillVersion, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: skillversion.Label}
	}
	return nil, &NotLoadedError{edge: "skill_version"}
}

// ContentBlobOrErr returns the ContentBlob value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SkillVersionFileEdges) ContentBlobOrErr() (*SkillBlob, error) {
	if e.ContentBlob != nil {
		return e.ContentBlob, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: skillblob.Label}
	}
	return nil, &NotLoadedError{edge: "content_blob"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SkillVersionFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case skillversionfile.FieldIsExecutable:
			values[i] = new(sql.NullBool)
		case skillversionfile.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case skillversionfile.FieldPath, skillversionfile.FieldFileKind, skillversionfile.FieldMediaType, skillversionfile.FieldEncoding, skillversionfile.FieldSha256:
			values[i] = new(sql.NullString)
		case skillversionfile.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case skillversionfile.FieldID, skillversionfile.FieldSkillVersionID, skillversionfile.FieldContentBlobID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SkillVersionFile fields.
func (_m *SkillVersionFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case skillversionfile.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case skillversionfile.FieldSkillVersionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field skill_version_id", values[i])
			} else if value != nil {
				_m.SkillVersionID = *value
			}
		case skillversionfile.FieldContentBlobID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field content_blob_id", values[i])
			} else if value != nil {
				_m.ContentBlobID = *value
			}
		case skillversionfile.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case skillversionfile.FieldFileKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_kind", values[i])
			} else if value.Valid {
				_m.FileKind = skillversionfile.FileKind(value.String)
			}
		case skillversionfile.FieldMediaType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_type", values[i])
			} else if value.Valid {
				_m.MediaType = value.String
			}
		case skillversionfile.FieldEncoding:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encoding", values[i])
			} else if value.Valid {
				_m.Encoding = skillversionfile.Encoding(value.String)
			}
		case skillversionfile.FieldIsExecutable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_executable", values[i])
			} else if value.Valid {
				_m.IsExecutable = value.Bool
			}
		case skillversionfile.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case skillversionfile.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case skillversionfile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SkillVersionFile.
// This includes values selected through modifiers, order, etc.
func (_m *SkillVersionFile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySkillVersion queries the "skill_version" edge of the SkillVersionFile entity.
func (_m *SkillVersionFile) QuerySkillVersion() *SkillVersionQuery {
	return NewSkillVersionFileClient(_m.config).QuerySkillVersion(_m)
}

// QueryContentBlob queries the "content_blob" edge of the SkillVersionFile entity.
func (_m *SkillVersionFile) QueryContentBlob() *SkillBlobQuery {
	return NewSkillVersionFileClient(_m.config).QueryContentBlob(_m)
}

// Update returns a builder for updating this SkillVersionFile.
// Note that you need to call SkillVersionFile.Unwrap() before calling this method if this SkillVersionFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SkillVersionFile) Update() *SkillVersionFileUpdateOne {
	return NewSkillVersionFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SkillVersionFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SkillVersionFile) Unwrap() *SkillVersionFile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SkillVersionFile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SkillVersionFile) String() string {
	var builder strings.Builder
	builder.WriteString("SkillVersionFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("skill_version_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillVersionID))
	builder.WriteString(", ")
	builder.WriteString("content_blob_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContentBlobID))
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("file_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileKind))
	builder.WriteString(", ")
	builder.WriteString("media_type=")
	builder.WriteString(_m.MediaType)
	builder.WriteString(", ")
	builder.WriteString("encoding=")
	builder.WriteString(fmt.Sprintf("%v", _m.Encoding))
	builder.WriteString(", ")
	builder.WriteString("is_executable=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsExecutable))
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SkillVersionFiles is a parsable slice of SkillVersionFile.
type SkillVersionFiles []*SkillVersionFile
