// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/predicate"
	"github.com/BetterAndBetterII/openase/ent/ticketcommentrevision"
)

// TicketCommentRevisionDelete is the builder for deleting a TicketCommentRevision entity.
type TicketCommentRevisionDelete struct {
	config
	hooks    []Hook
	mutation *TicketCommentRevisionMutation
}

// Where appends a list predicates to the TicketCommentRevisionDelete builder.
func (_d *TicketCommentRevisionDelete) Where(ps ...predicate.TicketCommentRevision) *TicketCommentRevisionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TicketCommentRevisionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TicketCommentRevisionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TicketCommentRevisionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ticketcommentrevision.Table, sqlgraph.NewFieldSpec(ticketcommentrevision.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TicketCommentRevisionDeleteOne is the builder for deleting a single TicketCommentRevision entity.
type TicketCommentRevisionDeleteOne struct {
	_d *TicketCommentRevisionDelete
}

// Where appends a list predicates to the TicketCommentRevisionDelete builder.
func (_d *TicketCommentRevisionDeleteOne) Where(ps ...predicate.TicketCommentRevision) *TicketCommentRevisionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TicketCommentRevisionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ticketcommentrevision.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TicketCommentRevisionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
