// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/predicate"
	"github.com/BetterAndBetterII/openase/ent/project"
	"github.com/BetterAndBetterII/openase/ent/ticketstage"
	"github.com/BetterAndBetterII/openase/ent/ticketstatus"
	"github.com/google/uuid"
)

// TicketStageUpdate is the builder for updating TicketStage entities.
type TicketStageUpdate struct {
	config
	hooks    []Hook
	mutation *TicketStageMutation
}

// Where appends a list predicates to the TicketStageUpdate builder.
func (_u *TicketStageUpdate) Where(ps ...predicate.TicketStage) *TicketStageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TicketStageUpdate) SetProjectID(v uuid.UUID) *TicketStageUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TicketStageUpdate) SetNillableProjectID(v *uuid.UUID) *TicketStageUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *TicketStageUpdate) SetKey(v string) *TicketStageUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TicketStageUpdate) SetNillableKey(v *string) *TicketStageUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TicketStageUpdate) SetName(v string) *TicketStageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TicketStageUpdate) SetNillableName(v *string) *TicketStageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *TicketStageUpdate) SetPosition(v int) *TicketStageUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *TicketStageUpdate) SetNillablePosition(v *int) *TicketStageUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *TicketStageUpdate) AddPosition(v int) *TicketStageUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetMaxActiveRuns sets the "max_active_runs" field.
func (_u *TicketStageUpdate) SetMaxActiveRuns(v int) *TicketStageUpdate {
	_u.mutation.ResetMaxActiveRuns()
	_u.mutation.SetMaxActiveRuns(v)
	return _u
}

// SetNillableMaxActiveRuns sets the "max_active_runs" field if the given value is not nil.
func (_u *TicketStageUpdate) SetNillableMaxActiveRuns(v *int) *TicketStageUpdate {
	if v != nil {
		_u.SetMaxActiveRuns(*v)
	}
	return _u
}

// AddMaxActiveRuns adds value to the "max_active_runs" field.
func (_u *TicketStageUpdate) AddMaxActiveRuns(v int) *TicketStageUpdate {
	_u.mutation.AddMaxActiveRuns(v)
	return _u
}

// ClearMaxActiveRuns clears the value of the "max_active_runs" field.
func (_u *TicketStageUpdate) ClearMaxActiveRuns() *TicketStageUpdate {
	_u.mutation.ClearMaxActiveRuns()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TicketStageUpdate) SetDescription(v string) *TicketStageUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TicketStageUpdate) SetNillableDescription(v *string) *TicketStageUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TicketStageUpdate) ClearDescription() *TicketStageUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TicketStageUpdate) SetProject(v *Project) *TicketStageUpdate {
	return _u.SetProjectID(v.ID)
}

// AddStatusIDs adds the "statuses" edge to the TicketStatus entity by IDs.
func (_u *TicketStageUpdate) AddStatusIDs(ids ...uuid.UUID) *TicketStageUpdate {
	_u.mutation.AddStatusIDs(ids...)
	return _u
}

// AddStatuses adds the "statuses" edges to the TicketStatus entity.
func (_u *TicketStageUpdate) AddStatuses(v ...*TicketStatus) *TicketStageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStatusIDs(ids...)
}

// Mutation returns the TicketStageMutation object of the builder.
func (_u *TicketStageUpdate) Mutation() *TicketStageMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TicketStageUpdate) ClearProject() *TicketStageUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearStatuses clears all "statuses" edges to the TicketStatus entity.
func (_u *TicketStageUpdate) ClearStatuses() *TicketStageUpdate {
	_u.mutation.ClearStatuses()
	return _u
}

// RemoveStatusIDs removes the "statuses" edge to TicketStatus entities by IDs.
func (_u *TicketStageUpdate) RemoveStatusIDs(ids ...uuid.UUID) *TicketStageUpdate {
	_u.mutation.RemoveStatusIDs(ids...)
	return _u
}

// RemoveStatuses removes "statuses" edges to TicketStatus entities.
func (_u *TicketStageUpdate) RemoveStatuses(v ...*TicketStatus) *TicketStageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStatusIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TicketStageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketStageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TicketStageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketStageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketStageUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := ticketstage.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TicketStage.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := ticketstage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TicketStage.name": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketStage.project"`)
	}
	return nil
}

func (_u *TicketStageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketstage.Table, ticketstage.Columns, sqlgraph.NewFieldSpec(ticketstage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(ticketstage.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ticketstage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(ticketstage.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(ticketstage.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxActiveRuns(); ok {
		_spec.SetField(ticketstage.FieldMaxActiveRuns, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxActiveRuns(); ok {
		_spec.AddField(ticketstage.FieldMaxActiveRuns, field.TypeInt, value)
	}
	if _u.mutation.MaxActiveRunsCleared() {
		_spec.ClearField(ticketstage.FieldMaxActiveRuns, field.TypeInt)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ticketstage.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ticketstage.FieldDescription, field.TypeString)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketstage.ProjectTable,
			Columns: []string{ticketstage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketstage.ProjectTable,
			Columns: []string{ticketstage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketstage.StatusesTable,
			Columns: []string{ticketstage.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketstatus.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatusesIDs(); len(nodes) > 0 && !_u.mutation.StatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketstage.StatusesTable,
			Columns: []string{ticketstage.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketstatus.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketstage.StatusesTable,
			Columns: []string{ticketstage.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketstatus.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketstage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TicketStageUpdateOne is the builder for updating a single TicketStage entity.
type TicketStageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketStageMutation
}

// SetProjectID sets the "project_id" field.
func (_u *TicketStageUpdateOne) SetProjectID(v uuid.UUID) *TicketStageUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TicketStageUpdateOne) SetNillableProjectID(v *uuid.UUID) *TicketStageUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *TicketStageUpdateOne) SetKey(v string) *TicketStageUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TicketStageUpdateOne) SetNillableKey(v *string) *TicketStageUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TicketStageUpdateOne) SetName(v string) *TicketStageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TicketStageUpdateOne) SetNillableName(v *string) *TicketStageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *TicketStageUpdateOne) SetPosition(v int) *TicketStageUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *TicketStageUpdateOne) SetNillablePosition(v *int) *TicketStageUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *TicketStageUpdateOne) AddPosition(v int) *TicketStageUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetMaxActiveRuns sets the "max_active_runs" field.
func (_u *TicketStageUpdateOne) SetMaxActiveRuns(v int) *TicketStageUpdateOne {
	_u.mutation.ResetMaxActiveRuns()
	_u.mutation.SetMaxActiveRuns(v)
	return _u
}

// SetNillableMaxActiveRuns sets the "max_active_runs" field if the given value is not nil.
func (_u *TicketStageUpdateOne) SetNillableMaxActiveRuns(v *int) *TicketStageUpdateOne {
	if v != nil {
		_u.SetMaxActiveRuns(*v)
	}
	return _u
}

// AddMaxActiveRuns adds value to the "max_active_runs" field.
func (_u *TicketStageUpdateOne) AddMaxActiveRuns(v int) *TicketStageUpdateOne {
	_u.mutation.AddMaxActiveRuns(v)
	return _u
}

// ClearMaxActiveRuns clears the value of the "max_active_runs" field.
func (_u *TicketStageUpdateOne) ClearMaxActiveRuns() *TicketStageUpdateOne {
	_u.mutation.ClearMaxActiveRuns()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TicketStageUpdateOne) SetDescription(v string) *TicketStageUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TicketStageUpdateOne) SetNillableDescription(v *string) *TicketStageUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TicketStageUpdateOne) ClearDescription() *TicketStageUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TicketStageUpdateOne) SetProject(v *Project) *TicketStageUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddStatusIDs adds the "statuses" edge to the TicketStatus entity by IDs.
func (_u *TicketStageUpdateOne) AddStatusIDs(ids ...uuid.UUID) *TicketStageUpdateOne {
	_u.mutation.AddStatusIDs(ids...)
	return _u
}

// AddStatuses adds the "statuses" edges to the TicketStatus entity.
func (_u *TicketStageUpdateOne) AddStatuses(v ...*TicketStatus) *TicketStageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStatusIDs(ids...)
}

// Mutation returns the TicketStageMutation object of the builder.
func (_u *TicketStageUpdateOne) Mutation() *TicketStageMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TicketStageUpdateOne) ClearProject() *TicketStageUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearStatuses clears all "statuses" edges to the TicketStatus entity.
func (_u *TicketStageUpdateOne) ClearStatuses() *TicketStageUpdateOne {
	_u.mutation.ClearStatuses()
	return _u
}

// RemoveStatusIDs removes the "statuses" edge to TicketStatus entities by IDs.
func (_u *TicketStageUpdateOne) RemoveStatusIDs(ids ...uuid.UUID) *TicketStageUpdateOne {
	_u.mutation.RemoveStatusIDs(ids...)
	return _u
}

// RemoveStatuses removes "statuses" edges to TicketStatus entities.
func (_u *TicketStageUpdateOne) RemoveStatuses(v ...*TicketStatus) *TicketStageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStatusIDs(ids...)
}

// Where appends a list predicates to the TicketStageUpdate builder.
func (_u *TicketStageUpdateOne) Where(ps ...predicate.TicketStage) *TicketStageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TicketStageUpdateOne) Select(field string, fields ...string) *TicketStageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TicketStage entity.
func (_u *TicketStageUpdateOne) Save(ctx context.Context) (*TicketStage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketStageUpdateOne) SaveX(ctx context.Context) *TicketStage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TicketStageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketStageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketStageUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := ticketstage.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TicketStage.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := ticketstage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TicketStage.name": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketStage.project"`)
	}
	return nil
}

func (_u *TicketStageUpdateOne) sqlSave(ctx context.Context) (_node *TicketStage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketstage.Table, ticketstage.Columns, sqlgraph.NewFieldSpec(ticketstage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TicketStage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticketstage.FieldID)
		for _, f := range fields {
			if !ticketstage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticketstage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(ticketstage.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ticketstage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(ticketstage.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(ticketstage.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxActiveRuns(); ok {
		_spec.SetField(ticketstage.FieldMaxActiveRuns, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxActiveRuns(); ok {
		_spec.AddField(ticketstage.FieldMaxActiveRuns, field.TypeInt, value)
	}
	if _u.mutation.MaxActiveRunsCleared() {
		_spec.ClearField(ticketstage.FieldMaxActiveRuns, field.TypeInt)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ticketstage.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ticketstage.FieldDescription, field.TypeString)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketstage.ProjectTable,
			Columns: []string{ticketstage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketstage.ProjectTable,
			Columns: []string{ticketstage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketstage.StatusesTable,
			Columns: []string{ticketstage.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketstatus.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatusesIDs(); len(nodes) > 0 && !_u.mutation.StatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketstage.StatusesTable,
			Columns: []string{ticketstage.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketstatus.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketstage.StatusesTable,
			Columns: []string{ticketstage.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketstatus.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TicketStage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketstage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
