// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sync"

	"entgo.io/ent/dialect"
)

// Tx is a transactional client that is created by calling Client.Tx().
type Tx struct {
	config
	// ActivityEvent is the client for interacting with the ActivityEvent builders.
	ActivityEvent *ActivityEventClient
	// Agent is the client for interacting with the Agent builders.
	Agent *AgentClient
	// AgentProvider is the client for interacting with the AgentProvider builders.
	AgentProvider *AgentProviderClient
	// AgentRun is the client for interacting with the AgentRun builders.
	AgentRun *AgentRunClient
	// AgentStepEvent is the client for interacting with the AgentStepEvent builders.
	AgentStepEvent *AgentStepEventClient
	// AgentToken is the client for interacting with the AgentToken builders.
	AgentToken *AgentTokenClient
	// AgentTraceEvent is the client for interacting with the AgentTraceEvent builders.
	AgentTraceEvent *AgentTraceEventClient
	// ApprovalPolicyRule is the client for interacting with the ApprovalPolicyRule builders.
	ApprovalPolicyRule *ApprovalPolicyRuleClient
	// BrowserSession is the client for interacting with the BrowserSession builders.
	BrowserSession *BrowserSessionClient
	// ChatConversation is the client for interacting with the ChatConversation builders.
	ChatConversation *ChatConversationClient
	// ChatEntry is the client for interacting with the ChatEntry builders.
	ChatEntry *ChatEntryClient
	// ChatPendingInterrupt is the client for interacting with the ChatPendingInterrupt builders.
	ChatPendingInterrupt *ChatPendingInterruptClient
	// ChatTurn is the client for interacting with the ChatTurn builders.
	ChatTurn *ChatTurnClient
	// Machine is the client for interacting with the Machine builders.
	Machine *MachineClient
	// MachineChannelToken is the client for interacting with the MachineChannelToken builders.
	MachineChannelToken *MachineChannelTokenClient
	// NotificationChannel is the client for interacting with the NotificationChannel builders.
	NotificationChannel *NotificationChannelClient
	// NotificationRule is the client for interacting with the NotificationRule builders.
	NotificationRule *NotificationRuleClient
	// Organization is the client for interacting with the Organization builders.
	Organization *OrganizationClient
	// OrganizationDailyTokenUsage is the client for interacting with the OrganizationDailyTokenUsage builders.
	OrganizationDailyTokenUsage *OrganizationDailyTokenUsageClient
	// Project is the client for interacting with the Project builders.
	Project *ProjectClient
	// ProjectConversationPrincipal is the client for interacting with the ProjectConversationPrincipal builders.
	ProjectConversationPrincipal *ProjectConversationPrincipalClient
	// ProjectConversationRun is the client for interacting with the ProjectConversationRun builders.
	ProjectConversationRun *ProjectConversationRunClient
	// ProjectConversationStepEvent is the client for interacting with the ProjectConversationStepEvent builders.
	ProjectConversationStepEvent *ProjectConversationStepEventClient
	// ProjectConversationTraceEvent is the client for interacting with the ProjectConversationTraceEvent builders.
	ProjectConversationTraceEvent *ProjectConversationTraceEventClient
	// ProjectRepo is the client for interacting with the ProjectRepo builders.
	ProjectRepo *ProjectRepoClient
	// ProjectUpdateComment is the client for interacting with the ProjectUpdateComment builders.
	ProjectUpdateComment *ProjectUpdateCommentClient
	// ProjectUpdateCommentRevision is the client for interacting with the ProjectUpdateCommentRevision builders.
	ProjectUpdateCommentRevision *ProjectUpdateCommentRevisionClient
	// ProjectUpdateThread is the client for interacting with the ProjectUpdateThread builders.
	ProjectUpdateThread *ProjectUpdateThreadClient
	// ProjectUpdateThreadRevision is the client for interacting with the ProjectUpdateThreadRevision builders.
	ProjectUpdateThreadRevision *ProjectUpdateThreadRevisionClient
	// RoleBinding is the client for interacting with the RoleBinding builders.
	RoleBinding *RoleBindingClient
	// ScheduledJob is the client for interacting with the ScheduledJob builders.
	ScheduledJob *ScheduledJobClient
	// Skill is the client for interacting with the Skill builders.
	Skill *SkillClient
	// SkillBlob is the client for interacting with the SkillBlob builders.
	SkillBlob *SkillBlobClient
	// SkillVersion is the client for interacting with the SkillVersion builders.
	SkillVersion *SkillVersionClient
	// SkillVersionFile is the client for interacting with the SkillVersionFile builders.
	SkillVersionFile *SkillVersionFileClient
	// Ticket is the client for interacting with the Ticket builders.
	Ticket *TicketClient
	// TicketComment is the client for interacting with the TicketComment builders.
	TicketComment *TicketCommentClient
	// TicketCommentRevision is the client for interacting with the TicketCommentRevision builders.
	TicketCommentRevision *TicketCommentRevisionClient
	// TicketDependency is the client for interacting with the TicketDependency builders.
	TicketDependency *TicketDependencyClient
	// TicketExternalLink is the client for interacting with the TicketExternalLink builders.
	TicketExternalLink *TicketExternalLinkClient
	// TicketRepoScope is the client for interacting with the TicketRepoScope builders.
	TicketRepoScope *TicketRepoScopeClient
	// TicketRepoWorkspace is the client for interacting with the TicketRepoWorkspace builders.
	TicketRepoWorkspace *TicketRepoWorkspaceClient
	// TicketStatus is the client for interacting with the TicketStatus builders.
	TicketStatus *TicketStatusClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserGroupMembership is the client for interacting with the UserGroupMembership builders.
	UserGroupMembership *UserGroupMembershipClient
	// UserIdentity is the client for interacting with the UserIdentity builders.
	UserIdentity *UserIdentityClient
	// Workflow is the client for interacting with the Workflow builders.
	Workflow *WorkflowClient
	// WorkflowSkillBinding is the client for interacting with the WorkflowSkillBinding builders.
	WorkflowSkillBinding *WorkflowSkillBindingClient
	// WorkflowVersion is the client for interacting with the WorkflowVersion builders.
	WorkflowVersion *WorkflowVersionClient

	// lazily loaded.
	client     *Client
	clientOnce sync.Once
	// ctx lives for the life of the transaction. It is
	// the same context used by the underlying connection.
	ctx context.Context
}

type (
	// Committer is the interface that wraps the Commit method.
	Committer interface {
		Commit(context.Context, *Tx) error
	}

	// The CommitFunc type is an adapter to allow the use of ordinary
	// function as a Committer. If f is a function with the appropriate
	// signature, CommitFunc(f) is a Committer that calls f.
	CommitFunc func(context.Context, *Tx) error

	// CommitHook defines the "commit middleware". A function that gets a Committer
	// and returns a Committer. For example:
	//
	//	hook := func(next ent.Committer) ent.Committer {
	//		return ent.CommitFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Commit(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	CommitHook func(Committer) Committer
)

// Commit calls f(ctx, m).
func (f CommitFunc) Commit(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Commit commits the transaction.
func (tx *Tx) Commit() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Committer = CommitFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Commit()
	})
	txDriver.mu.Lock()
	hooks := append([]CommitHook(nil), txDriver.onCommit...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Commit(tx.ctx, tx)
}

// OnCommit adds a hook to call on commit.
func (tx *Tx) OnCommit(f CommitHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onCommit = append(txDriver.onCommit, f)
	txDriver.mu.Unlock()
}

type (
	// Rollbacker is the interface that wraps the Rollback method.
	Rollbacker interface {
		Rollback(context.Context, *Tx) error
	}

	// The RollbackFunc type is an adapter to allow the use of ordinary
	// function as a Rollbacker. If f is a function with the appropriate
	// signature, RollbackFunc(f) is a Rollbacker that calls f.
	RollbackFunc func(context.Context, *Tx) error

	// RollbackHook defines the "rollback middleware". A function that gets a Rollbacker
	// and returns a Rollbacker. For example:
	//
	//	hook := func(next ent.Rollbacker) ent.Rollbacker {
	//		return ent.RollbackFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Rollback(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	RollbackHook func(Rollbacker) Rollbacker
)

// Rollback calls f(ctx, m).
func (f RollbackFunc) Rollback(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Rollback rollbacks the transaction.
func (tx *Tx) Rollback() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Rollbacker = RollbackFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Rollback()
	})
	txDriver.mu.Lock()
	hooks := append([]RollbackHook(nil), txDriver.onRollback...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Rollback(tx.ctx, tx)
}

// OnRollback adds a hook to call on rollback.
func (tx *Tx) OnRollback(f RollbackHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onRollback = append(txDriver.onRollback, f)
	txDriver.mu.Unlock()
}

// Client returns a Client that binds to current transaction.
func (tx *Tx) Client() *Client {
	tx.clientOnce.Do(func() {
		tx.client = &Client{config: tx.config}
		tx.client.init()
	})
	return tx.client
}

func (tx *Tx) init() {
	tx.ActivityEvent = NewActivityEventClient(tx.config)
	tx.Agent = NewAgentClient(tx.config)
	tx.AgentProvider = NewAgentProviderClient(tx.config)
	tx.AgentRun = NewAgentRunClient(tx.config)
	tx.AgentStepEvent = NewAgentStepEventClient(tx.config)
	tx.AgentToken = NewAgentTokenClient(tx.config)
	tx.AgentTraceEvent = NewAgentTraceEventClient(tx.config)
	tx.ApprovalPolicyRule = NewApprovalPolicyRuleClient(tx.config)
	tx.BrowserSession = NewBrowserSessionClient(tx.config)
	tx.ChatConversation = NewChatConversationClient(tx.config)
	tx.ChatEntry = NewChatEntryClient(tx.config)
	tx.ChatPendingInterrupt = NewChatPendingInterruptClient(tx.config)
	tx.ChatTurn = NewChatTurnClient(tx.config)
	tx.Machine = NewMachineClient(tx.config)
	tx.MachineChannelToken = NewMachineChannelTokenClient(tx.config)
	tx.NotificationChannel = NewNotificationChannelClient(tx.config)
	tx.NotificationRule = NewNotificationRuleClient(tx.config)
	tx.Organization = NewOrganizationClient(tx.config)
	tx.OrganizationDailyTokenUsage = NewOrganizationDailyTokenUsageClient(tx.config)
	tx.Project = NewProjectClient(tx.config)
	tx.ProjectConversationPrincipal = NewProjectConversationPrincipalClient(tx.config)
	tx.ProjectConversationRun = NewProjectConversationRunClient(tx.config)
	tx.ProjectConversationStepEvent = NewProjectConversationStepEventClient(tx.config)
	tx.ProjectConversationTraceEvent = NewProjectConversationTraceEventClient(tx.config)
	tx.ProjectRepo = NewProjectRepoClient(tx.config)
	tx.ProjectUpdateComment = NewProjectUpdateCommentClient(tx.config)
	tx.ProjectUpdateCommentRevision = NewProjectUpdateCommentRevisionClient(tx.config)
	tx.ProjectUpdateThread = NewProjectUpdateThreadClient(tx.config)
	tx.ProjectUpdateThreadRevision = NewProjectUpdateThreadRevisionClient(tx.config)
	tx.RoleBinding = NewRoleBindingClient(tx.config)
	tx.ScheduledJob = NewScheduledJobClient(tx.config)
	tx.Skill = NewSkillClient(tx.config)
	tx.SkillBlob = NewSkillBlobClient(tx.config)
	tx.SkillVersion = NewSkillVersionClient(tx.config)
	tx.SkillVersionFile = NewSkillVersionFileClient(tx.config)
	tx.Ticket = NewTicketClient(tx.config)
	tx.TicketComment = NewTicketCommentClient(tx.config)
	tx.TicketCommentRevision = NewTicketCommentRevisionClient(tx.config)
	tx.TicketDependency = NewTicketDependencyClient(tx.config)
	tx.TicketExternalLink = NewTicketExternalLinkClient(tx.config)
	tx.TicketRepoScope = NewTicketRepoScopeClient(tx.config)
	tx.TicketRepoWorkspace = NewTicketRepoWorkspaceClient(tx.config)
	tx.TicketStatus = NewTicketStatusClient(tx.config)
	tx.User = NewUserClient(tx.config)
	tx.UserGroupMembership = NewUserGroupMembershipClient(tx.config)
	tx.UserIdentity = NewUserIdentityClient(tx.config)
	tx.Workflow = NewWorkflowClient(tx.config)
	tx.WorkflowSkillBinding = NewWorkflowSkillBindingClient(tx.config)
	tx.WorkflowVersion = NewWorkflowVersionClient(tx.config)
}

// txDriver wraps the given dialect.Tx with a nop dialect.Driver implementation.
// The idea is to support transactions without adding any extra code to the builders.
// When a builder calls to driver.Tx(), it gets the same dialect.Tx instance.
// Commit and Rollback are nop for the internal builders and the user must call one
// of them in order to commit or rollback the transaction.
//
// If a closed transaction is embedded in one of the generated entities, and the entity
// applies a query, for example: ActivityEvent.QueryXXX(), the query will be executed
// through the driver which created this transaction.
//
// Note that txDriver is not goroutine safe.
type txDriver struct {
	// the driver we started the transaction from.
	drv dialect.Driver
	// tx is the underlying transaction.
	tx dialect.Tx
	// completion hooks.
	mu         sync.Mutex
	onCommit   []CommitHook
	onRollback []RollbackHook
}

// newTx creates a new transactional driver.
func newTx(ctx context.Context, drv dialect.Driver) (*txDriver, error) {
	tx, err := drv.Tx(ctx)
	if err != nil {
		return nil, err
	}
	return &txDriver{tx: tx, drv: drv}, nil
}

// Tx returns the transaction wrapper (txDriver) to avoid Commit or Rollback calls
// from the internal builders. Should be called only by the internal builders.
func (tx *txDriver) Tx(context.Context) (dialect.Tx, error) { return tx, nil }

// Dialect returns the dialect of the driver we started the transaction from.
func (tx *txDriver) Dialect() string { return tx.drv.Dialect() }

// Close is a nop close.
func (*txDriver) Close() error { return nil }

// Commit is a nop commit for the internal builders.
// User must call `Tx.Commit` in order to commit the transaction.
func (*txDriver) Commit() error { return nil }

// Rollback is a nop rollback for the internal builders.
// User must call `Tx.Rollback` in order to rollback the transaction.
func (*txDriver) Rollback() error { return nil }

// Exec calls tx.Exec.
func (tx *txDriver) Exec(ctx context.Context, query string, args, v any) error {
	return tx.tx.Exec(ctx, query, args, v)
}

// Query calls tx.Query.
func (tx *txDriver) Query(ctx context.Context, query string, args, v any) error {
	return tx.tx.Query(ctx, query, args, v)
}

var _ dialect.Driver = (*txDriver)(nil)
