// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BetterAndBetterII/openase/ent/predicate"
	"github.com/BetterAndBetterII/openase/ent/workflowskillbinding"
)

// WorkflowSkillBindingDelete is the builder for deleting a WorkflowSkillBinding entity.
type WorkflowSkillBindingDelete struct {
	config
	hooks    []Hook
	mutation *WorkflowSkillBindingMutation
}

// Where appends a list predicates to the WorkflowSkillBindingDelete builder.
func (_d *WorkflowSkillBindingDelete) Where(ps ...predicate.WorkflowSkillBinding) *WorkflowSkillBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WorkflowSkillBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkflowSkillBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WorkflowSkillBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workflowskillbinding.Table, sqlgraph.NewFieldSpec(workflowskillbinding.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WorkflowSkillBindingDeleteOne is the builder for deleting a single WorkflowSkillBinding entity.
type WorkflowSkillBindingDeleteOne struct {
	_d *WorkflowSkillBindingDelete
}

// Where appends a list predicates to the WorkflowSkillBindingDelete builder.
func (_d *WorkflowSkillBindingDeleteOne) Where(ps ...predicate.WorkflowSkillBinding) *WorkflowSkillBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WorkflowSkillBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workflowskillbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkflowSkillBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
