// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/BetterAndBetterII/openase/ent/workflow"
	"github.com/BetterAndBetterII/openase/ent/workflowversion"
	"github.com/google/uuid"
)

// WorkflowVersion is the model entity for the WorkflowVersion schema.
type WorkflowVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID uuid.UUID `json:"workflow_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// ContentMarkdown holds the value of the "content_markdown" field.
	ContentMarkdown string `json:"content_markdown,omitempty"`
	// ContentHash holds the value of the "content_hash" field.
	ContentHash string `json:"content_hash,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkflowVersionQuery when eager-loading is set.
	Edges        WorkflowVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WorkflowVersionEdges holds the relations/edges for other nodes in the graph.
type WorkflowVersionEdges struct {
	// Workflow holds the value of the workflow edge.
	Workflow *Workflow `json:"workflow,omitempty"`
	// RequiredByBindings holds the value of the required_by_bindings edge.
	RequiredByBindings []*WorkflowSkillBinding `json:"required_by_bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// WorkflowOrErr returns the Workflow value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkflowVersionEdges) WorkflowOrErr() (*Workflow, error) {
	if e.Workflow != nil {
		return e.Workflow, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workflow.Label}
	}
	return nil, &NotLoadedError{edge: "workflow"}
}

// RequiredByBindingsOrErr returns the RequiredByBindings value or an error if the edge
// was not loaded in eager-loading.
func (e WorkflowVersionEdges) RequiredByBindingsOrErr() ([]*WorkflowSkillBinding, error) {
	if e.loadedTypes[1] {
		return e.RequiredByBindings, nil
	}
	return nil, &NotLoadedError{edge: "required_by_bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflowversion.FieldVersion:
			values[i] = new(sql.NullInt64)
		case workflowversion.FieldContentMarkdown, workflowversion.FieldContentHash, workflowversion.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case workflowversion.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case workflowversion.FieldID, workflowversion.FieldWorkflowID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowVersion fields.
func (_m *WorkflowVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflowversion.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case workflowversion.FieldWorkflowID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value != nil {
				_m.WorkflowID = *value
			}
		case workflowversion.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case workflowversion.FieldContentMarkdown:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_markdown", values[i])
			} else if value.Valid {
				_m.ContentMarkdown = value.String
			}
		case workflowversion.FieldContentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_hash", values[i])
			} else if value.Valid {
				_m.ContentHash = value.String
			}
		case workflowversion.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case workflowversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowVersion.
// This includes values selected through modifiers, order, etc.
func (_m *WorkflowVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkflow queries the "workflow" edge of the WorkflowVersion entity.
func (_m *WorkflowVersion) QueryWorkflow() *WorkflowQuery {
	return NewWorkflowVersionClient(_m.config).QueryWorkflow(_m)
}

// QueryRequiredByBindings queries the "required_by_bindings" edge of the WorkflowVersion entity.
func (_m *WorkflowVersion) QueryRequiredByBindings() *WorkflowSkillBindingQuery {
	return NewWorkflowVersionClient(_m.config).QueryRequiredByBindings(_m)
}

// Update returns a builder for updating this WorkflowVersion.
// Note that you need to call WorkflowVersion.Unwrap() before calling this method if this WorkflowVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkflowVersion) Update() *WorkflowVersionUpdateOne {
	return NewWorkflowVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkflowVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkflowVersion) Unwrap() *WorkflowVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkflowVersion) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("workflow_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkflowID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("content_markdown=")
	builder.WriteString(_m.ContentMarkdown)
	builder.WriteString(", ")
	builder.WriteString("content_hash=")
	builder.WriteString(_m.ContentHash)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowVersions is a parsable slice of WorkflowVersion.
type WorkflowVersions []*WorkflowVersion
