/** Map file extension to a Shiki/CodeMirror language identifier. */
export function detectLanguage(filePath: string): string {
  const ext = filePath.split('.').pop()?.toLowerCase() ?? ''
  const map: Record<string, string> = {
    ts: 'typescript',
    tsx: 'tsx',
    js: 'javascript',
    jsx: 'jsx',
    mjs: 'javascript',
    cjs: 'javascript',
    json: 'json',
    jsonc: 'json',
    yaml: 'yaml',
    yml: 'yaml',
    md: 'markdown',
    mdx: 'mdx',
    html: 'html',
    htm: 'html',
    css: 'css',
    scss: 'scss',
    less: 'less',
    py: 'python',
    rb: 'ruby',
    rs: 'rust',
    go: 'go',
    java: 'java',
    kt: 'kotlin',
    swift: 'swift',
    c: 'c',
    cpp: 'cpp',
    h: 'c',
    hpp: 'cpp',
    cs: 'csharp',
    sh: 'shellscript',
    bash: 'shellscript',
    zsh: 'shellscript',
    fish: 'fish',
    sql: 'sql',
    graphql: 'graphql',
    gql: 'graphql',
    xml: 'xml',
    svg: 'xml',
    toml: 'toml',
    ini: 'ini',
    env: 'dotenv',
    dockerfile: 'dockerfile',
    docker: 'dockerfile',
    makefile: 'makefile',
    svelte: 'svelte',
    vue: 'vue',
    php: 'php',
    lua: 'lua',
    zig: 'zig',
    proto: 'protobuf',
    tf: 'hcl',
    hcl: 'hcl',
    diff: 'diff',
    patch: 'diff',
  }
  // Handle extensionless filenames like Dockerfile, Makefile
  const basename = filePath.split('/').pop()?.toLowerCase() ?? ''
  if (basename === 'dockerfile') return 'dockerfile'
  if (basename === 'makefile' || basename === 'gnumakefile') return 'makefile'
  return map[ext] ?? 'text'
}
