// Code generated by ent, DO NOT EDIT.

package projectconversationprincipal

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/BetterAndBetterII/openase/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldID, id))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldConversationID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldProjectID, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldProviderID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldName, v))
}

// CurrentSessionID applies equality check predicate on the "current_session_id" field. It's identical to CurrentSessionIDEQ.
func CurrentSessionID(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentSessionID, v))
}

// CurrentWorkspacePath applies equality check predicate on the "current_workspace_path" field. It's identical to CurrentWorkspacePathEQ.
func CurrentWorkspacePath(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentWorkspacePath, v))
}

// CurrentRunID applies equality check predicate on the "current_run_id" field. It's identical to CurrentRunIDEQ.
func CurrentRunID(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentRunID, v))
}

// LastHeartbeatAt applies equality check predicate on the "last_heartbeat_at" field. It's identical to LastHeartbeatAtEQ.
func LastHeartbeatAt(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// CurrentStepStatus applies equality check predicate on the "current_step_status" field. It's identical to CurrentStepStatusEQ.
func CurrentStepStatus(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentStepStatus, v))
}

// CurrentStepSummary applies equality check predicate on the "current_step_summary" field. It's identical to CurrentStepSummaryEQ.
func CurrentStepSummary(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentStepSummary, v))
}

// CurrentStepChangedAt applies equality check predicate on the "current_step_changed_at" field. It's identical to CurrentStepChangedAtEQ.
func CurrentStepChangedAt(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentStepChangedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldClosedAt, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldConversationID, vs...))
}

// ConversationIDGT applies the GT predicate on the "conversation_id" field.
func ConversationIDGT(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldConversationID, v))
}

// ConversationIDGTE applies the GTE predicate on the "conversation_id" field.
func ConversationIDGTE(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldConversationID, v))
}

// ConversationIDLT applies the LT predicate on the "conversation_id" field.
func ConversationIDLT(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldConversationID, v))
}

// ConversationIDLTE applies the LTE predicate on the "conversation_id" field.
func ConversationIDLTE(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldConversationID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldProjectID, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldProviderID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldStatus, vs...))
}

// RuntimeStateEQ applies the EQ predicate on the "runtime_state" field.
func RuntimeStateEQ(v RuntimeState) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldRuntimeState, v))
}

// RuntimeStateNEQ applies the NEQ predicate on the "runtime_state" field.
func RuntimeStateNEQ(v RuntimeState) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldRuntimeState, v))
}

// RuntimeStateIn applies the In predicate on the "runtime_state" field.
func RuntimeStateIn(vs ...RuntimeState) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldRuntimeState, vs...))
}

// RuntimeStateNotIn applies the NotIn predicate on the "runtime_state" field.
func RuntimeStateNotIn(vs ...RuntimeState) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldRuntimeState, vs...))
}

// CurrentSessionIDEQ applies the EQ predicate on the "current_session_id" field.
func CurrentSessionIDEQ(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentSessionID, v))
}

// CurrentSessionIDNEQ applies the NEQ predicate on the "current_session_id" field.
func CurrentSessionIDNEQ(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldCurrentSessionID, v))
}

// CurrentSessionIDIn applies the In predicate on the "current_session_id" field.
func CurrentSessionIDIn(vs ...string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldCurrentSessionID, vs...))
}

// CurrentSessionIDNotIn applies the NotIn predicate on the "current_session_id" field.
func CurrentSessionIDNotIn(vs ...string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldCurrentSessionID, vs...))
}

// CurrentSessionIDGT applies the GT predicate on the "current_session_id" field.
func CurrentSessionIDGT(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldCurrentSessionID, v))
}

// CurrentSessionIDGTE applies the GTE predicate on the "current_session_id" field.
func CurrentSessionIDGTE(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldCurrentSessionID, v))
}

// CurrentSessionIDLT applies the LT predicate on the "current_session_id" field.
func CurrentSessionIDLT(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldCurrentSessionID, v))
}

// CurrentSessionIDLTE applies the LTE predicate on the "current_session_id" field.
func CurrentSessionIDLTE(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldCurrentSessionID, v))
}

// CurrentSessionIDContains applies the Contains predicate on the "current_session_id" field.
func CurrentSessionIDContains(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldContains(FieldCurrentSessionID, v))
}

// CurrentSessionIDHasPrefix applies the HasPrefix predicate on the "current_session_id" field.
func CurrentSessionIDHasPrefix(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldHasPrefix(FieldCurrentSessionID, v))
}

// CurrentSessionIDHasSuffix applies the HasSuffix predicate on the "current_session_id" field.
func CurrentSessionIDHasSuffix(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldHasSuffix(FieldCurrentSessionID, v))
}

// CurrentSessionIDIsNil applies the IsNil predicate on the "current_session_id" field.
func CurrentSessionIDIsNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIsNull(FieldCurrentSessionID))
}

// CurrentSessionIDNotNil applies the NotNil predicate on the "current_session_id" field.
func CurrentSessionIDNotNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotNull(FieldCurrentSessionID))
}

// CurrentSessionIDEqualFold applies the EqualFold predicate on the "current_session_id" field.
func CurrentSessionIDEqualFold(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEqualFold(FieldCurrentSessionID, v))
}

// CurrentSessionIDContainsFold applies the ContainsFold predicate on the "current_session_id" field.
func CurrentSessionIDContainsFold(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldContainsFold(FieldCurrentSessionID, v))
}

// CurrentWorkspacePathEQ applies the EQ predicate on the "current_workspace_path" field.
func CurrentWorkspacePathEQ(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentWorkspacePath, v))
}

// CurrentWorkspacePathNEQ applies the NEQ predicate on the "current_workspace_path" field.
func CurrentWorkspacePathNEQ(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldCurrentWorkspacePath, v))
}

// CurrentWorkspacePathIn applies the In predicate on the "current_workspace_path" field.
func CurrentWorkspacePathIn(vs ...string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldCurrentWorkspacePath, vs...))
}

// CurrentWorkspacePathNotIn applies the NotIn predicate on the "current_workspace_path" field.
func CurrentWorkspacePathNotIn(vs ...string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldCurrentWorkspacePath, vs...))
}

// CurrentWorkspacePathGT applies the GT predicate on the "current_workspace_path" field.
func CurrentWorkspacePathGT(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldCurrentWorkspacePath, v))
}

// CurrentWorkspacePathGTE applies the GTE predicate on the "current_workspace_path" field.
func CurrentWorkspacePathGTE(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldCurrentWorkspacePath, v))
}

// CurrentWorkspacePathLT applies the LT predicate on the "current_workspace_path" field.
func CurrentWorkspacePathLT(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldCurrentWorkspacePath, v))
}

// CurrentWorkspacePathLTE applies the LTE predicate on the "current_workspace_path" field.
func CurrentWorkspacePathLTE(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldCurrentWorkspacePath, v))
}

// CurrentWorkspacePathContains applies the Contains predicate on the "current_workspace_path" field.
func CurrentWorkspacePathContains(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldContains(FieldCurrentWorkspacePath, v))
}

// CurrentWorkspacePathHasPrefix applies the HasPrefix predicate on the "current_workspace_path" field.
func CurrentWorkspacePathHasPrefix(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldHasPrefix(FieldCurrentWorkspacePath, v))
}

// CurrentWorkspacePathHasSuffix applies the HasSuffix predicate on the "current_workspace_path" field.
func CurrentWorkspacePathHasSuffix(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldHasSuffix(FieldCurrentWorkspacePath, v))
}

// CurrentWorkspacePathIsNil applies the IsNil predicate on the "current_workspace_path" field.
func CurrentWorkspacePathIsNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIsNull(FieldCurrentWorkspacePath))
}

// CurrentWorkspacePathNotNil applies the NotNil predicate on the "current_workspace_path" field.
func CurrentWorkspacePathNotNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotNull(FieldCurrentWorkspacePath))
}

// CurrentWorkspacePathEqualFold applies the EqualFold predicate on the "current_workspace_path" field.
func CurrentWorkspacePathEqualFold(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEqualFold(FieldCurrentWorkspacePath, v))
}

// CurrentWorkspacePathContainsFold applies the ContainsFold predicate on the "current_workspace_path" field.
func CurrentWorkspacePathContainsFold(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldContainsFold(FieldCurrentWorkspacePath, v))
}

// CurrentRunIDEQ applies the EQ predicate on the "current_run_id" field.
func CurrentRunIDEQ(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentRunID, v))
}

// CurrentRunIDNEQ applies the NEQ predicate on the "current_run_id" field.
func CurrentRunIDNEQ(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldCurrentRunID, v))
}

// CurrentRunIDIn applies the In predicate on the "current_run_id" field.
func CurrentRunIDIn(vs ...uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldCurrentRunID, vs...))
}

// CurrentRunIDNotIn applies the NotIn predicate on the "current_run_id" field.
func CurrentRunIDNotIn(vs ...uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldCurrentRunID, vs...))
}

// CurrentRunIDGT applies the GT predicate on the "current_run_id" field.
func CurrentRunIDGT(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldCurrentRunID, v))
}

// CurrentRunIDGTE applies the GTE predicate on the "current_run_id" field.
func CurrentRunIDGTE(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldCurrentRunID, v))
}

// CurrentRunIDLT applies the LT predicate on the "current_run_id" field.
func CurrentRunIDLT(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldCurrentRunID, v))
}

// CurrentRunIDLTE applies the LTE predicate on the "current_run_id" field.
func CurrentRunIDLTE(v uuid.UUID) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldCurrentRunID, v))
}

// CurrentRunIDIsNil applies the IsNil predicate on the "current_run_id" field.
func CurrentRunIDIsNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIsNull(FieldCurrentRunID))
}

// CurrentRunIDNotNil applies the NotNil predicate on the "current_run_id" field.
func CurrentRunIDNotNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotNull(FieldCurrentRunID))
}

// LastHeartbeatAtEQ applies the EQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtEQ(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtNEQ applies the NEQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNEQ(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIn applies the In predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIn(vs ...time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtNotIn applies the NotIn predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotIn(vs ...time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtGT applies the GT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGT(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtGTE applies the GTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGTE(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLT applies the LT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLT(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLTE applies the LTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLTE(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIsNil applies the IsNil predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIsNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIsNull(FieldLastHeartbeatAt))
}

// LastHeartbeatAtNotNil applies the NotNil predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotNull(FieldLastHeartbeatAt))
}

// CurrentStepStatusEQ applies the EQ predicate on the "current_step_status" field.
func CurrentStepStatusEQ(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentStepStatus, v))
}

// CurrentStepStatusNEQ applies the NEQ predicate on the "current_step_status" field.
func CurrentStepStatusNEQ(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldCurrentStepStatus, v))
}

// CurrentStepStatusIn applies the In predicate on the "current_step_status" field.
func CurrentStepStatusIn(vs ...string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldCurrentStepStatus, vs...))
}

// CurrentStepStatusNotIn applies the NotIn predicate on the "current_step_status" field.
func CurrentStepStatusNotIn(vs ...string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldCurrentStepStatus, vs...))
}

// CurrentStepStatusGT applies the GT predicate on the "current_step_status" field.
func CurrentStepStatusGT(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldCurrentStepStatus, v))
}

// CurrentStepStatusGTE applies the GTE predicate on the "current_step_status" field.
func CurrentStepStatusGTE(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldCurrentStepStatus, v))
}

// CurrentStepStatusLT applies the LT predicate on the "current_step_status" field.
func CurrentStepStatusLT(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldCurrentStepStatus, v))
}

// CurrentStepStatusLTE applies the LTE predicate on the "current_step_status" field.
func CurrentStepStatusLTE(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldCurrentStepStatus, v))
}

// CurrentStepStatusContains applies the Contains predicate on the "current_step_status" field.
func CurrentStepStatusContains(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldContains(FieldCurrentStepStatus, v))
}

// CurrentStepStatusHasPrefix applies the HasPrefix predicate on the "current_step_status" field.
func CurrentStepStatusHasPrefix(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldHasPrefix(FieldCurrentStepStatus, v))
}

// CurrentStepStatusHasSuffix applies the HasSuffix predicate on the "current_step_status" field.
func CurrentStepStatusHasSuffix(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldHasSuffix(FieldCurrentStepStatus, v))
}

// CurrentStepStatusIsNil applies the IsNil predicate on the "current_step_status" field.
func CurrentStepStatusIsNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIsNull(FieldCurrentStepStatus))
}

// CurrentStepStatusNotNil applies the NotNil predicate on the "current_step_status" field.
func CurrentStepStatusNotNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotNull(FieldCurrentStepStatus))
}

// CurrentStepStatusEqualFold applies the EqualFold predicate on the "current_step_status" field.
func CurrentStepStatusEqualFold(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEqualFold(FieldCurrentStepStatus, v))
}

// CurrentStepStatusContainsFold applies the ContainsFold predicate on the "current_step_status" field.
func CurrentStepStatusContainsFold(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldContainsFold(FieldCurrentStepStatus, v))
}

// CurrentStepSummaryEQ applies the EQ predicate on the "current_step_summary" field.
func CurrentStepSummaryEQ(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentStepSummary, v))
}

// CurrentStepSummaryNEQ applies the NEQ predicate on the "current_step_summary" field.
func CurrentStepSummaryNEQ(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldCurrentStepSummary, v))
}

// CurrentStepSummaryIn applies the In predicate on the "current_step_summary" field.
func CurrentStepSummaryIn(vs ...string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldCurrentStepSummary, vs...))
}

// CurrentStepSummaryNotIn applies the NotIn predicate on the "current_step_summary" field.
func CurrentStepSummaryNotIn(vs ...string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldCurrentStepSummary, vs...))
}

// CurrentStepSummaryGT applies the GT predicate on the "current_step_summary" field.
func CurrentStepSummaryGT(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldCurrentStepSummary, v))
}

// CurrentStepSummaryGTE applies the GTE predicate on the "current_step_summary" field.
func CurrentStepSummaryGTE(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldCurrentStepSummary, v))
}

// CurrentStepSummaryLT applies the LT predicate on the "current_step_summary" field.
func CurrentStepSummaryLT(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldCurrentStepSummary, v))
}

// CurrentStepSummaryLTE applies the LTE predicate on the "current_step_summary" field.
func CurrentStepSummaryLTE(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldCurrentStepSummary, v))
}

// CurrentStepSummaryContains applies the Contains predicate on the "current_step_summary" field.
func CurrentStepSummaryContains(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldContains(FieldCurrentStepSummary, v))
}

// CurrentStepSummaryHasPrefix applies the HasPrefix predicate on the "current_step_summary" field.
func CurrentStepSummaryHasPrefix(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldHasPrefix(FieldCurrentStepSummary, v))
}

// CurrentStepSummaryHasSuffix applies the HasSuffix predicate on the "current_step_summary" field.
func CurrentStepSummaryHasSuffix(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldHasSuffix(FieldCurrentStepSummary, v))
}

// CurrentStepSummaryIsNil applies the IsNil predicate on the "current_step_summary" field.
func CurrentStepSummaryIsNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIsNull(FieldCurrentStepSummary))
}

// CurrentStepSummaryNotNil applies the NotNil predicate on the "current_step_summary" field.
func CurrentStepSummaryNotNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotNull(FieldCurrentStepSummary))
}

// CurrentStepSummaryEqualFold applies the EqualFold predicate on the "current_step_summary" field.
func CurrentStepSummaryEqualFold(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEqualFold(FieldCurrentStepSummary, v))
}

// CurrentStepSummaryContainsFold applies the ContainsFold predicate on the "current_step_summary" field.
func CurrentStepSummaryContainsFold(v string) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldContainsFold(FieldCurrentStepSummary, v))
}

// CurrentStepChangedAtEQ applies the EQ predicate on the "current_step_changed_at" field.
func CurrentStepChangedAtEQ(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCurrentStepChangedAt, v))
}

// CurrentStepChangedAtNEQ applies the NEQ predicate on the "current_step_changed_at" field.
func CurrentStepChangedAtNEQ(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldCurrentStepChangedAt, v))
}

// CurrentStepChangedAtIn applies the In predicate on the "current_step_changed_at" field.
func CurrentStepChangedAtIn(vs ...time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldCurrentStepChangedAt, vs...))
}

// CurrentStepChangedAtNotIn applies the NotIn predicate on the "current_step_changed_at" field.
func CurrentStepChangedAtNotIn(vs ...time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldCurrentStepChangedAt, vs...))
}

// CurrentStepChangedAtGT applies the GT predicate on the "current_step_changed_at" field.
func CurrentStepChangedAtGT(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldCurrentStepChangedAt, v))
}

// CurrentStepChangedAtGTE applies the GTE predicate on the "current_step_changed_at" field.
func CurrentStepChangedAtGTE(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldCurrentStepChangedAt, v))
}

// CurrentStepChangedAtLT applies the LT predicate on the "current_step_changed_at" field.
func CurrentStepChangedAtLT(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldCurrentStepChangedAt, v))
}

// CurrentStepChangedAtLTE applies the LTE predicate on the "current_step_changed_at" field.
func CurrentStepChangedAtLTE(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldCurrentStepChangedAt, v))
}

// CurrentStepChangedAtIsNil applies the IsNil predicate on the "current_step_changed_at" field.
func CurrentStepChangedAtIsNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIsNull(FieldCurrentStepChangedAt))
}

// CurrentStepChangedAtNotNil applies the NotNil predicate on the "current_step_changed_at" field.
func CurrentStepChangedAtNotNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotNull(FieldCurrentStepChangedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldUpdatedAt, v))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.FieldNotNull(FieldClosedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectConversationPrincipal) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectConversationPrincipal) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectConversationPrincipal) predicate.ProjectConversationPrincipal {
	return predicate.ProjectConversationPrincipal(sql.NotPredicates(p))
}
