import type {
  ProjectRepoPayload,
  StatusPayload,
  TicketDetailPayload,
  TicketPayload,
  WorkflowListPayload,
} from '$lib/api/contracts'
import { detailPickupDiagnosisFixture } from './context.test-fixtures.pickup-diagnosis'

export const detailPayloadFixture: TicketDetailPayload = {
  assigned_agent: {
    id: 'agent-1',
    name: 'todo-app-coding-01',
    provider: 'codex-cloud',
    runtime_control_state: 'active',
    runtime_phase: 'executing',
  },
  pickup_diagnosis: detailPickupDiagnosisFixture,
  ticket: {
    id: 'ticket-1',
    project_id: 'project-1',
    identifier: 'ASE-1',
    title: 'Implement ticket detail agent binding',
    description: '',
    status_id: 'status-1',
    status_name: 'Todo',
    priority: 'high',
    type: 'bugfix',
    archived: false,
    workflow_id: 'workflow-1',
    current_run_id: 'run-1',
    target_machine_id: null,
    created_by: 'user:test',
    parent: null,
    children: [],
    dependencies: [
      {
        id: 'dep-1',
        type: 'blocked_by',
        target: {
          id: 'ticket-2',
          identifier: 'ASE-2',
          title: 'Backend migration',
          status_id: 'status-2',
          status_name: 'In Progress',
        },
      },
      {
        id: 'dep-2',
        type: 'blocks',
        target: {
          id: 'ticket-3',
          identifier: 'ASE-3',
          title: 'Frontend polish',
          status_id: 'status-3',
          status_name: 'Done',
        },
      },
    ],
    external_links: [],
    pull_request_urls: [],
    external_ref: '',
    budget_usd: 0,
    cost_tokens_input: 1444743,
    cost_tokens_output: 23322,
    cost_tokens_total: 1468065,
    cost_amount: 0,
    attempt_count: 0,
    consecutive_errors: 0,
    started_at: null,
    completed_at: null,
    next_retry_at: null,
    retry_paused: false,
    pause_reason: '',
    created_at: '2026-03-27T12:00:00Z',
  },
  repo_scopes: [],
  comments: [],
  timeline: [
    {
      id: 'description:ticket-1',
      ticket_id: 'ticket-1',
      item_type: 'description',
      actor_name: 'user:test',
      actor_type: 'user',
      title: 'Implement ticket detail agent binding',
      body_markdown: '',
      body_text: null,
      created_at: '2026-03-27T12:00:00Z',
      updated_at: '2026-03-27T12:00:00Z',
      edited_at: null,
      is_collapsible: false,
      is_deleted: false,
      metadata: {
        identifier: 'ASE-1',
      },
    },
    {
      id: 'comment:comment-1',
      ticket_id: 'ticket-1',
      item_type: 'comment',
      actor_name: 'user:reviewer',
      actor_type: 'user',
      title: null,
      body_markdown: 'LGTM',
      body_text: null,
      created_at: '2026-03-27T12:05:00Z',
      updated_at: '2026-03-27T12:10:00Z',
      edited_at: '2026-03-27T12:10:00Z',
      is_collapsible: true,
      is_deleted: false,
      metadata: {
        edit_count: 1,
        revision_count: 2,
        last_edited_by: 'user:reviewer',
      },
    },
    {
      id: 'activity:event-1',
      ticket_id: 'ticket-1',
      item_type: 'activity',
      actor_name: 'dispatcher',
      actor_type: 'system',
      title: 'pr.opened',
      body_markdown: null,
      body_text: 'Opened frontend PR #9',
      created_at: '2026-03-27T12:06:00Z',
      updated_at: '2026-03-27T12:06:00Z',
      edited_at: null,
      is_collapsible: true,
      is_deleted: false,
      metadata: {
        event_type: 'pr.opened',
        pull_request_url: 'https://github.com/acme/frontend/pull/9',
      },
    },
  ],
  activity: [],
  hook_history: [],
}

export const statusPayloadFixture: StatusPayload = {
  statuses: [
    {
      id: 'status-1',
      project_id: 'project-1',
      name: 'Todo',
      stage: 'unstarted',
      color: '#2563eb',
      icon: '',
      is_default: true,
      description: '',
      position: 1,
      active_runs: 0,
      max_active_runs: null,
    },
    {
      id: 'status-2',
      project_id: 'project-1',
      name: 'In Progress',
      stage: 'started',
      color: '#f59e0b',
      icon: '',
      is_default: false,
      description: '',
      position: 2,
      active_runs: 0,
      max_active_runs: null,
    },
    {
      id: 'status-3',
      project_id: 'project-1',
      name: 'Done',
      stage: 'completed',
      color: '#10b981',
      icon: '',
      is_default: false,
      description: '',
      position: 3,
      active_runs: 0,
      max_active_runs: null,
    },
  ],
}

export const workflowPayloadFixture: WorkflowListPayload = {
  workflows: [
    {
      id: 'workflow-1',
      project_id: 'project-1',
      agent_id: 'agent-1',
      name: 'Todo App Coding Workflow',
      type: 'coding',
      workflow_family: 'coding',
      workflow_classification: {
        family: 'coding',
        confidence: 1,
        reasons: ['fixture'],
      },
      harness_path: '.openase/harnesses/todo.md',
      harness_content: null,
      hooks: {},
      max_concurrent: 1,
      max_retry_attempts: 0,
      timeout_minutes: 30,
      stall_timeout_minutes: 10,
      version: 1,
      is_active: true,
      pickup_status_ids: ['status-1'],
      finish_status_ids: ['status-2'],
    },
  ],
}

export const repoPayloadFixture: ProjectRepoPayload = {
  repos: [],
}

export const ticketPayloadFixture: TicketPayload = {
  tickets: [
    {
      id: 'ticket-1',
      project_id: 'project-1',
      identifier: 'ASE-1',
      title: 'Implement ticket detail agent binding',
      description: '',
      status_id: 'status-1',
      status_name: 'Todo',
      priority: 'high',
      type: 'bugfix',
      archived: false,
      workflow_id: 'workflow-1',
      current_run_id: 'run-1',
      target_machine_id: null,
      created_by: 'user:test',
      parent: null,
      children: [],
      dependencies: [],
      external_links: [],
      pull_request_urls: [],
      external_ref: '',
      budget_usd: 0,
      cost_tokens_input: 0,
      cost_tokens_output: 0,
      cost_tokens_total: 0,
      cost_amount: 0,
      attempt_count: 0,
      consecutive_errors: 0,
      started_at: null,
      completed_at: null,
      next_retry_at: null,
      retry_paused: false,
      pause_reason: '',
      created_at: '2026-03-27T12:00:00Z',
    },
    {
      id: 'ticket-2',
      project_id: 'project-1',
      identifier: 'ASE-2',
      title: 'Backend migration',
      description: '',
      status_id: 'status-2',
      status_name: 'In Progress',
      priority: 'medium',
      type: 'feature',
      archived: false,
      workflow_id: null,
      current_run_id: null,
      target_machine_id: null,
      created_by: 'user:test',
      parent: null,
      children: [],
      dependencies: [],
      external_links: [],
      pull_request_urls: [],
      external_ref: '',
      budget_usd: 0,
      cost_tokens_input: 0,
      cost_tokens_output: 0,
      cost_tokens_total: 0,
      cost_amount: 0,
      attempt_count: 0,
      consecutive_errors: 0,
      started_at: null,
      completed_at: null,
      next_retry_at: null,
      retry_paused: false,
      pause_reason: '',
      created_at: '2026-03-27T12:00:00Z',
    },
  ],
}
