// Code generated by ent, DO NOT EDIT.

package projectrepomirror

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the projectrepomirror type in the database.
	Label = "project_repo_mirror"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectRepoID holds the string denoting the project_repo_id field in the database.
	FieldProjectRepoID = "project_repo_id"
	// FieldMachineID holds the string denoting the machine_id field in the database.
	FieldMachineID = "machine_id"
	// FieldLocalPath holds the string denoting the local_path field in the database.
	FieldLocalPath = "local_path"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldHeadCommit holds the string denoting the head_commit field in the database.
	FieldHeadCommit = "head_commit"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldLastVerifiedAt holds the string denoting the last_verified_at field in the database.
	FieldLastVerifiedAt = "last_verified_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProjectRepo holds the string denoting the project_repo edge name in mutations.
	EdgeProjectRepo = "project_repo"
	// EdgeMachine holds the string denoting the machine edge name in mutations.
	EdgeMachine = "machine"
	// EdgeTicketRepoWorkspaces holds the string denoting the ticket_repo_workspaces edge name in mutations.
	EdgeTicketRepoWorkspaces = "ticket_repo_workspaces"
	// Table holds the table name of the projectrepomirror in the database.
	Table = "project_repo_mirrors"
	// ProjectRepoTable is the table that holds the project_repo relation/edge.
	ProjectRepoTable = "project_repo_mirrors"
	// ProjectRepoInverseTable is the table name for the ProjectRepo entity.
	// It exists in this package in order to avoid circular dependency with the "projectrepo" package.
	ProjectRepoInverseTable = "project_repos"
	// ProjectRepoColumn is the table column denoting the project_repo relation/edge.
	ProjectRepoColumn = "project_repo_id"
	// MachineTable is the table that holds the machine relation/edge.
	MachineTable = "project_repo_mirrors"
	// MachineInverseTable is the table name for the Machine entity.
	// It exists in this package in order to avoid circular dependency with the "machine" package.
	MachineInverseTable = "machines"
	// MachineColumn is the table column denoting the machine relation/edge.
	MachineColumn = "machine_id"
	// TicketRepoWorkspacesTable is the table that holds the ticket_repo_workspaces relation/edge.
	TicketRepoWorkspacesTable = "ticket_repo_workspaces"
	// TicketRepoWorkspacesInverseTable is the table name for the TicketRepoWorkspace entity.
	// It exists in this package in order to avoid circular dependency with the "ticketrepoworkspace" package.
	TicketRepoWorkspacesInverseTable = "ticket_repo_workspaces"
	// TicketRepoWorkspacesColumn is the table column denoting the ticket_repo_workspaces relation/edge.
	TicketRepoWorkspacesColumn = "mirror_id"
)

// Columns holds all SQL columns for projectrepomirror fields.
var Columns = []string{
	FieldID,
	FieldProjectRepoID,
	FieldMachineID,
	FieldLocalPath,
	FieldState,
	FieldHeadCommit,
	FieldLastSyncedAt,
	FieldLastVerifiedAt,
	FieldLastError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LocalPathValidator is a validator for the "local_path" field. It is called by the builders before save.
	LocalPathValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// State defines the type for the "state" enum field.
type State string

// StateMissing is the default value of the State enum.
const DefaultState = StateMissing

// State values.
const (
	StateMissing      State = "missing"
	StateProvisioning State = "provisioning"
	StateReady        State = "ready"
	StateStale        State = "stale"
	StateSyncing      State = "syncing"
	StateError        State = "error"
	StateDeleting     State = "deleting"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateMissing, StateProvisioning, StateReady, StateStale, StateSyncing, StateError, StateDeleting:
		return nil
	default:
		return fmt.Errorf("projectrepomirror: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the ProjectRepoMirror queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectRepoID orders the results by the project_repo_id field.
func ByProjectRepoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectRepoID, opts...).ToFunc()
}

// ByMachineID orders the results by the machine_id field.
func ByMachineID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMachineID, opts...).ToFunc()
}

// ByLocalPath orders the results by the local_path field.
func ByLocalPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalPath, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByHeadCommit orders the results by the head_commit field.
func ByHeadCommit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeadCommit, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByLastVerifiedAt orders the results by the last_verified_at field.
func ByLastVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastVerifiedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectRepoField orders the results by project_repo field.
func ByProjectRepoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectRepoStep(), sql.OrderByField(field, opts...))
	}
}

// ByMachineField orders the results by machine field.
func ByMachineField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMachineStep(), sql.OrderByField(field, opts...))
	}
}

// ByTicketRepoWorkspacesCount orders the results by ticket_repo_workspaces count.
func ByTicketRepoWorkspacesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTicketRepoWorkspacesStep(), opts...)
	}
}

// ByTicketRepoWorkspaces orders the results by ticket_repo_workspaces terms.
func ByTicketRepoWorkspaces(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTicketRepoWorkspacesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProjectRepoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectRepoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectRepoTable, ProjectRepoColumn),
	)
}
func newMachineStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MachineInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MachineTable, MachineColumn),
	)
}
func newTicketRepoWorkspacesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TicketRepoWorkspacesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TicketRepoWorkspacesTable, TicketRepoWorkspacesColumn),
	)
}
